### ISSUE TITLE
Secret value not referenced if upstream chart doesn't use `tpl` function

### ISSUE THREAD

**Issue by megakoresh** [jkroepke/helm-secrets#103]
In a use-case where I have my `secrets.yaml` like this

```yaml
postgresPassword: !vault secrets/superset#postgresPassword
```

and then I am trying to deploy [superset](https://github.com/apache/superset) chart and in my values I set

```yaml
postgresql:
  postgresqlPassword: '{{ .Values.postgresPassword }}'
```

for the dependency chart, the generated secret is

```yaml
# Source: superset/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.2.0
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgresql-password: "e3sgLlZhbHVlcy5wb3N0Z3Jlc1Bhc3N3b3JkIH19"
```

which corresponds literally to `{{ .Values.postgresPassword }}`. This is because the dependency chart doesn't use `tpl` to refer to this value and of course I can't control it. Same issue exists for the superset chart itself. Where the chart templates refer to values via `tpl` function, the value from secret is correctly rendered.

I am using the following command to check:

```zsh
helm secrets -d vault upgrade --install superset .tmp/superset-master/helm/superset -f superset/prod/secrets.yaml -f superset/prod/values.yaml --dry-run
```

Am I just doing something wrong or is this an issue with the plugin?
