### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by tgruenert** [jkroepke/helm-secrets#130]
In some cases decrypted content is printed in one line but original it was a multiline entry.

an example:
```
# Administrator credentials when not using an existing secret (see below)
grafana:
    ldap:
        config: |-
            # query example 
            # (&(ObjectClass=posixAccount)(uid=username)(memberOf=cn=groupname,ou=groups,dc=domain,dc=de))
            group_search_filter = '(&(objectClass=posixGroup)(uniqueMember=%s))'
            group_search_filter_user_attribute = 'uid'
            group_search_base_dns = ['ou=Gruppen,dc=domain,dc=de']
            # ## Group search filter, to retrieve the groups of which the user is a member (only set if memberOf attribute is not available)
            # group_search_filter = '(&(objectClass=posixGroup)(memberUid=%s))'
            # ## An array of the base DNs to search through for groups. Typically uses ou=groups
            # group_search_base_dns = ['ou=Gruppen,dc=domain,dc=de']
            # ## the %s in the search filter will be replaced with the attribute defined below
            # group_search_filter_user_attribute = 'uid'

```
after `helm secrets edit filename.yaml`
```
# Administrator credentials when not using an existing secret (see below)
grafana:
    ldap:
        config: "# query example \n# (&(ObjectClass=posixAccount)(uid=username)(memberOf=cn=groupname,ou=Gruppen,dc=domain,dc=de))\ngroup_search_filter = '(&(objectClass=posixGroup)(uniqueMember=%s))'\ngroup_search_filter_user_attribute = 'uid'\ngroup_search_base_dns = ['ou=Gruppen,dc=domain,dc=de']\n# ## Group search filter, to retrieve the groups of which the user is a member (only set if memberOf attribute is not available)\n# group_search_filter = '(&(objectClass=posixGroup)(memberUid=%s))'\n# ## An array of the base DNs to search through for groups. Typically uses ou=groups\n# group_search_base_dns = ['ou=Gruppen,dc=domain,dc=de']\n# ## the %s in the search filter will be replaced with the attribute defined below\n# group_search_filter_user_attribute = 'uid'"
```
Have you a work around for this or better - a fix?

Thank anybody for supporting this and for developing this smart tool further.
