### ISSUE TITLE
encrypting voilating yaml is possible but decrypting not

### ISSUE THREAD

**Issue by tgruenert** [jkroepke/helm-secrets#131]
In case of human mistake you may lose your secrets (ok. this is possible for all kind of human and technical things ;-) ).

given yaml:
```
mistakeLevel:
  foo: bar
mistakeLevel:
  foo2: bar2
```

This will encrypted and looks like 
```
mistakeLevel:
    foo: ENC[AES256_GCM,data:kqbu,iv:mNoiQHiftiKhkrpJEwBybLG123WGtk1KFxlAF/R/Hdo=,tag:x+7tNtSXKaZ2nV+hzOXMLw==,type:str]
mistakeLevel:
    foo2: ENC[AES256_GCM,data:0shAng==,iv:Rj0+QPDnUcoZHDsGkOuD9RgX9qCSHuL5xzL5cR4u1cw=,tag:mEanDBW1MOc+L0uZGKbivA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
...
```

So far so nice.
```
$ helm secrets edit filename.yaml
filename.yaml
Error unmarshalling input yaml: yaml: unmarshal errors:
  line 3: mapping key "mistakeLevel" already defined at line 1
Error: plugin "secrets" exited with error
```

So better have a second source for your secrets or make no mistakes ;-).

One possible point may this:
before encoding and closing file try to decode file without error. This may a simple check procedure to prevent such a situation. But i dont be a developer so i can´t give you a PR for this.
