### ISSUE TITLE
Support for ArgoCD

### ISSUE THREAD

**Issue by mmenbawy** [jkroepke/helm-secrets#134]
How can helm secrets run via ArgoCD?

This is not working https://github.com/jkroepke/helm-secrets#argocd-support

**Comment by jarrettprosser** [comment]
You'll need to add helm secrets as an Argo [plugin](https://argoproj.github.io/argo-cd/user-guide/config-management-plugins/). I use the following. The init command imports the gpg key, the generate uses template to render the manifests. 
```
data:
      configManagementPlugins: |
        - name: helm3-secrets
          init: 
            command: ["/bin/sh", "-c"]
            args: ["gpg --import /opt/helm-secrets-config/helm-secrets.key && gpg --export-secret-keys > ~/.gnupg/secring.gpg || true"]
          generate:
            command: ["/bin/sh", "-c"]
            args: ["helm secrets template -f values.yaml -f secrets.yaml $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE ."]
```
Then tell the Argo application to use the plugin:
```
spec:
  source:
    plugin:
      name: helm3-secrets
```
