### ISSUE TITLE
Failed to get the data key required to decrypt the SOPS file

### ISSUE THREAD

**Issue by sebtiz13** [jkroepke/helm-secrets#146]
### Current Behavior

When I try to deploy an applications on argo-cd with secret like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: git@example.com:user/my-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
```

I have an error from SOPS
```
 failed exit status 2: Failed to get the data key required to decrypt the SOPS file. Group 0: FAILED 42884C51FAE6259CA8BABC4363F0C9212B8974F0: FAILED - | could not decrypt data key with PGP key: | golang.org/x/crypto/openpgp error: Could not load secring: | open /app/config/gpg/keys/secring.gpg: no such file or | directory; GPG binary error: exit status 2 Recovery failed because no master key was able to decrypt the file. In order for SOPS to recover the file, at least one key has to be successful, but none were. panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae9207] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile(0xc000135890, 0x16, 0xc0006efe80, 0x3, 0x4, 0xc0000a1400, 0x0, 0x0, 0x0, 0x0) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x167 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc0004a4360, 0xc0006efe80, 0x3, 0x4, 0x1, 0x33, 0x0) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x115 main.runInstall(0xc00065c000, 0x1, 0x7e, 0xc00041a2c0, 0xc0004a4360, 0x2292040, 0xc000182008, 0x0, 0x1ffdae6, 0xa) helm.sh/helm/v3/cmd/helm/install.go:193 +0x24e main.newTemplateCmd.func2(0xc0004e8500, 0xc00065c000, 0x1, 0x7e, 0x0, 0x0) helm.sh/helm/v3/cmd/helm/template.go:82 +0x146 github.com/spf13/cobra.(*Command).execute(0xc0004e8500, 0xc00032b800, 0x7e, 0x80, 0xc0004e8500, 0xc00032b800) github.com/spf13/cobra@v1.1.3/command.go:852 +0x472 github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fe500, 0xc00013e1b0, 0x1, 0xc00079ff60) github.com/spf13/cobra@v1.1.3/command.go:960 +0x375 github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.1.3/command.go:897 main.main() helm.sh/helm/v3/cmd/helm/helm.go:80 +0x25b
```

### Expected Behavior

Secrets file are decrypt with gpg keys added on argo-cd

### Steps To Reproduce

1. deploy argo-cd with [helm chart](https://argoproj.github.io/argo-helm)
2. configure init container to install helm-secrets and sops

```yaml
repoServer:
    env:
    - name: HELM_PLUGINS
      value: /app/helm-plugins/
  volumes:
    - name: custom-tools
      emptyDir: {}

  initContainers:
    - name: download-tools
      image: alpine:3.8
      command: [sh, -c]
      args:
        - |
          apk add curl && cd /custom-tools;
          echo "Install binaries"
          curl -fSSL https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux -o sops && chmod +x sops;
          
          echo "Install plugins"
          mkdir -p /custom-tools/helm-plugins && cd /custom-tools/helm-plugins;
          echo "Install helm-secrets"
          curl -LsSf https://github.com/jkroepke/helm-secrets/releases/download/v3.8.3/helm-secrets.tar.gz | tar -xzf-;
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/sops
      name: custom-tools
      subPath: sops
    - mountPath: /app/helm-plugins/
      name: custom-tools
      subPath: helm-plugins
```
3) add your gpg key to argocd and try to deploy an application with encrypted secret

### Environment

* argocd 2.1.2

### Anything else?

Sorry i cant retrieve where i found this configuration.

**Comment by jkroepke** [comment]
Hi!

Could you please verify if you private is available inside ArgoCD?

https://argo-cd.readthedocs.io/en/stable/user-guide/gpg-verification/#gnupg-key-ring


```bash
# Replace with correct pod name
kubectl exec -it argocd-repo-server-7d6bdfdf6d-hzqkg bash
GNUPGHOME=/app/config/gpg/keys gpg --list-secret-keys
GNUPGHOME=/app/config/gpg/keys gpg --list-secret-keys 42884C51FAE6259CA8BABC4363F0C9212B8974F0
```

**Comment by sebtiz13** [comment]
Hello thanks for your fast response.

It's appear that my key it's not available on `--list-secret-keys` I have just
```
gpg: WARNING: unsafe ownership on homedir '/app/config/gpg/keys'
/app/config/gpg/keys/pubring.kbx
--------------------------------
sec   rsa2048 2021-10-03 [SC] [expires: 2022-04-01]
      9573AF85A8E05DB5B02CD77D98D7AF17ED2D03C8
uid           [ultimate] Anon Ymous (ArgoCD key signing key) <noreply@argoproj.io>
```

but she is available on `--list-keys`
```
$ GNUPGHOME=/app/config/gpg/keys gpg --list-keys
gpg: WARNING: unsafe ownership on homedir '/app/config/gpg/keys'
/app/config/gpg/keys/pubring.kbx
--------------------------------
pub   rsa2048 2021-10-03 [SC] [expires: 2022-04-01]
      9573AF85A8E05DB5B02CD77D98D7AF17ED2D03C8
uid           [ultimate] Anon Ymous (ArgoCD key signing key) <noreply@argoproj.io>

pub   rsa3072 2021-10-03 [SC]
      42884C51FAE6259CA8BABC4363F0C9212B8974F0
uid           [ultimate] Sebastien Rodriguez <contact@example.com>

$ GNUPGHOME=/app/config/gpg/keys gpg --list-keys 42884C51FAE6259CA8BABC4363F0C9212B8974F0
gpg: WARNING: unsafe ownership on homedir '/app/config/gpg/keys'
pub   rsa3072 2021-10-03 [SC]
      42884C51FAE6259CA8BABC4363F0C9212B8974F0
uid           [ultimate] Sebastien Rodriguez <contact@example.com>
sub   rsa3072 2021-10-03 [E]
```

Sorry, I am new with GnuPG keys. I have supposed if my key are available on `--list-keys` It's good. But I supposed only secrets keys can decrypt the files. I have forgotten something for that ?

**Comment by jkroepke** [comment]
GPG keys are asymmetric. Public keys (gpg --list-keys) are used to encrypt values, Private keys (gpg --list-secret-keys) are used to decrypt values.

Have the public key (gpg --list-keys) inside argocd repo server wont have any effect here.

Private keys in PEM format are always like this:

```yaml
-----BEGIN PGP PRIVATE KEY BLOCK-----

...
-----END PGP PRIVATE KEY BLOCK-----
```

Currently I'm not using helm-secrets and argo together. I can not help here. But by reading the docs:

- The ArgoCD Web Ui supports only gpg public keys, you can not use the UI the add the gpg key
- Based on that, you need to mount the key from external secrets. Checkout [this](https://github.com/camptocamp/docker-argocd#using-sops-with-a-gpg-key).

**Comment by jkroepke** [comment]
Today, I installed ArgoCD and do some test with helm-secrets.

I agree, importing gpg keys is quite complex, I couldn't find a working solution todo it.

Based on that, I'm create https://github.com/jkroepke/helm-secrets/pull/147

This PR introduce the functionality of importing gpg keys on demand.

gpg private keys need to be still mounted on the repo-server pod, but helm-secrets is able to import them as required.

**Comment by jkroepke** [comment]
Hi @sebtiz13 

since #147 is merged, I can now successfully run helm-secrets with ArgoCD.

Note: I'm using main branch here. I would create a release of helm-secret you can give some feedback of success.

1. create a secret with the gpg private key:

```bash
kubectl create secret generic gpg-private-keys --from-file=app.asc=path/to/private-key.asc
```

Verify, that `path/to/private-key.asc` is like:

```
-----BEGIN PGP PRIVATE KEY BLOCK-----

...
-----END PGP PRIVATE KEY BLOCK-----
```

2. Deploy ArgoCD, using the values:
```yaml
repoServer:
  env:
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_SOPS_BIN
      value: /custom-tools/sops

  volumes:
    - name: custom-tools
      emptyDir: {}

    - name: gpg-private-keys
      secret:
        secretName: gpg-private-keys

  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

    - mountPath: /gpg-private-keys/
      name: gpg-private-keys

  initContainers:
    - name: download-tools
      image: alpine:latest
      command: [sh, -ec]
      env:
        - name: SOPS_VERSION
          value: "3.7.1"
        - name: HELM_SECRETS_VERSION
          value: "3.8.3"
      args:
        - |
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
          chmod +x /custom-tools/sops
          mkdir -p /custom-tools/helm-plugins
          # wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-
          wget -qO- https://github.com/jkroepke/helm-secrets/archive/refs/heads/main.tar.gz | tar -C /custom-tools/helm-plugins -xzf-
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
```

3. Change the values inside your ArgoCD Application to this
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argo-cd
...
      valueFiles:
        - values.yaml
        - 'gpg-import+secrets:///gpg-private-keys/app.asc?secrets.yaml'
```

With the combination of all, ArgoCD is able to decrypt and sync the manifest.

See also: https://github.com/jkroepke/helm-secrets/blob/main/docs/ARGOCD.md

**Comment by sebtiz13** [comment]
Hi @jkroepke.

Sorry for my mistake for the gpg keys, I'm beginner with gpg.

Yes load private Key on Argo CD are not realy

**Comment by sebtiz13** [comment]
Hi @jkroepke.

Sorry for my mistake for the gpg keys, I'm beginner with gpg.

Yes use private Key on Argo CD it's not simple. I have seen this solution https://faun.pub/handling-kubernetes-secrets-with-argocd-and-sops-650df91de173 He rename helm binary and use an wrapper where he load an gpg key.

But I prefer your approach, I find it's more flexible and more explicit.I can easily mount multiples keys to use on diferent projects In my case each developer can have her Key for her deployments.

But I have seen kubectl in install and kubernetes "protocole" im not certain how use that and i haven't see On doc

**Comment by jkroepke** [comment]
> But I have seen kubectl in install and kubernetes "protocole" im not certain how use that

For know, I would prefer the `secrets+gpg-import://`, since `secrets+gpg-import-kubernetes://` isn't fully tested for now. But this avoid the requirement of mounting the gpg keys in argocd. You can add and remove gpg keys without restarting ArgoCD.

>  and i haven't see On doc

I extend the docs https://github.com/jkroepke/helm-secrets/blob/main/docs/ARGOCD.md, maybe now it's more helpful.

**Comment by sebtiz13** [comment]
Ok I understand, so it's considered like preview feature.

I think I'm going test this to give you an feedback on that. If he can avoid the necessity to restart Argo CD to add a Keys it's can be pretty cool.
Even if I don't need to add more every day.

Thanks for this documentation. I check that as soon as possible

**Comment by sebtiz13** [comment]
Hello,
So for fast test I have add

In my helm charts Argo CD
```yaml
repoServer:
  rbac:
  - apiGroups:
    - ""
    resources:
    - secret
    verbs:
    - get
    - list
    - watch
```

secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gpg-private-keys
  namespace: argo-cd
type: Opaque
data:
  63F0C9212B8974F0.asc: LS0tLS...
```
valuesFile:
```
secrets+gpg-import-kubernetes://argo-cd/gpg-private-keys#63F0C9212B8974F0.asc?secrets.yaml
```

and I have this error
```
failed exit status 2: Error from server (Forbidden): secrets "gpg-private-keys" is forbidden: User "system:serviceaccount:argo-cd:default" cannot get resource "secrets" in API group "" in the namespace "argo-cd" panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1ae9207] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile(0xc000189500, 0x5a, 0xc00050eb80, 0x3, 0x4, 0xc00075b000, 0x0, 0x0, 0x0, 0x0) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x167 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc000027500, 0xc00050eb80, 0x3, 0x4, 0x1, 0x3e, 0x0) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x115 main.runInstall(0xc0002f4800, 0x1, 0x80, 0xc00044f4a0, 0xc000027500, 0x2292040, 0xc00000e018, 0x4b2d4a, 0x1ff75ab, 0x6) helm.sh/helm/v3/cmd/helm/install.go:193 +0x24e main.newTemplateCmd.func2(0xc00017ef00, 0xc0002f4800, 0x1, 0x80, 0x0, 0x0) helm.sh/helm/v3/cmd/helm/template.go:82 +0x146 github.com/spf13/cobra.(*Command).execute(0xc00017ef00, 0xc0002f4000, 0x80, 0x80, 0xc00017ef00, 0xc0002f4000) github.com/spf13/cobra@v1.1.3/command.go:852 +0x472 github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d0c80, 0xc00000f8b8, 0x1, 0xc00081ff60) github.com/spf13/cobra@v1.1.3/command.go:960 +0x375 github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.1.3/command.go:897 main.main() helm.sh/helm/v3/cmd/helm/helm.go:80 +0x25b
```

I see it's an problem of permission, maybe `rbac` are not correct. I learn too on this part so I'm going to seach
