### ISSUE TITLE
Error when installing secrets encrypted with age

### ISSUE THREAD

**Issue by a-dot** [jkroepke/helm-secrets#192]
### Current Behavior

Hi, I generated age keys in key.txt and encrypted a test secrets in templates/secrets.yaml. I get an error when trying to install the chart that includes the encrypted Secret. See below.

### Expected Behavior

I shouldn't get an error on install.

### Steps To Reproduce

```markdown
[ ~/mychart]$ export SOPS_AGE_KEY_FILE=/home/blah/mychart/key.txt
[ ~/mychart]$ export SOPS_AGE_RECIPIENTS=age1ju90kke0mncldqcsc4mrvlq3snuuqt0htn706raw4vvtc8u4r97qj2rr3u
[ ~/mychart]$ helm secrets enc templates/secrets.yaml
Encrypting templates/secrets.yaml
Encrypted secrets.yaml
[ ~/mychart]$ helm upgrade -i testrelease . -f 'secrets+age-import://key.txt?templates/secrets.yaml'
Release "testrelease" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ENC[AES256_GCM,data:7La03wOQ,iv:K1MVcCpTZrocCwmyiHSDTZa+oAocz4U7Wkwcinr2Z4k=,tag:xZvsmYJz10bOM6kOglbnhg==,type:str]" in version "ENC[AES256_GCM,data:Fwk=,iv:pLG9fXiyz2+AfaINd9evjYUOTIPZPdCIPTlxaFkoA8U=,tag:JMQuEMJKbIfN5XuJkWvmjw==,type:str]"
```

### Environment

- Helm Version: 3.7.0
- Helm Secrets Version: 3.12.0
- OS: Ubuntu
- Shell: Bash

**Comment by jkroepke** [comment]
can you provide the metadata of the secrets.yaml file? (just stip the values)

**Comment by a-dot** [comment]
Sure! Thanks for the quick reply!

Plaintext:
```
apiVersion: v1
kind: Secret
metadata:
    name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
    username: admin
    password: t0p-Secret
```

Encrypted:
```
apiVersion: ENC[AES256_GCM,data:Fwk=,iv:pLG9fXiyz2+AfaINd9evjYUOTIPZPdCIPTlxaFkoA8U=,tag:JMQuEMJKbIfN5XuJkWvmjw==,type:str]
kind: ENC[AES256_GCM,data:7La03wOQ,iv:K1MVcCpTZrocCwmyiHSDTZa+oAocz4U7Wkwcinr2Z4k=,tag:xZvsmYJz10bOM6kOglbnhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EyrXb7KWnpAsUXh5oPq85Us=,iv:kXVyAkDqYjBApOQh/s7wIHyPtixpRbgNOAHMX69Qq2U=,tag:SAE1ippjIUKPwxAK8TNcdw==,type:str]
type: ENC[AES256_GCM,data:+SoFRCMp8j473qmiN0MPuy7jHrdRz+bu,iv:DmmzIcmNxQ3WWaMylA8wcxT5ovQne2nSDQ/nDoBDPIg=,tag:kCl6POqpjGRVW8RtE72LPA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Ol7p3OE=,iv:ohjPIyh0HEqCVMrtBwOGlBt2APxpJW3eOwRM//5CTbM=,tag:g2S5FcTIautf6tHs5Dg6fw==,type:str]
    password: ENC[AES256_GCM,data:AUEp3I/EY6+5/w==,iv:ESVnLx60qa/avdPZxViOo0yDcjsAnxIoqH17ovMCfFw=,tag:ONzRGyw4Hlnuem4YW142sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ju90kke0mncldqcsc4mrvlq3snuuqt0htn706raw4vvtc8u4r97qj2rr3u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWURPSkRBa1NsSU1ENUts
            a1ZoVXRaSFVwVjJzYmU5Z1JZQWNwMXUrbTFBCkI2d09TK0tkMWsvc01PNFpIeTdE
            Yk5xOVFEU0JDaWIzOHZZKzdzUzM0ZncKLS0tIFhqNEhnOXBLb1dTUzdqTEN1VzEw
            YkNEVS9hQnFYZ0s2dVFxbHUrbUYyNHMKGhGk3SP33dV2YiFd7esQHc51x3WsLwE1
            4zVhoUtqPiFNtUxyylWfhiW56qZGcbK3ZYG+Ems7DZC1wjhugs0dXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-18T18:24:46Z"
    mac: ENC[AES256_GCM,data:ybXL2uthWl6YBVW1Bz2kiLzNY9FAtZt6loCTUwvtQN8GJK53xq73KD5GrBMPK+iq8vCT/l2G1Fj2TEz6Z5FrJ/c0sTRKMMjy9nOKeirMVZPUeWQTIOz5tYhLkH1YN0d7cN4kk/0Yo0g+zOKsTdKnpi4GVB7Z4htOZwXq5FJsHQU=,iv:25O9qrMbuKRHXw93EjuY0Q2XaWgj0dTMa4FL0nZiE5g=,tag:iBXe0Z7tkJh4PeA7ks4y+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
```
