### ISSUE TITLE
Running on Windows fails

### ISSUE THREAD

**Issue by sherifkayad** [jkroepke/helm-secrets#214]
### Current Behavior

When I install the plugin using Helm on Windows (using a MINGW terminal) and I attempt to run my `helm` command, there's an error as follows:
```
Error: fork/exec C:\Users\MY_USER\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh: %1 is not a valid Win32 application.
``` 

My Helm command after installing the plugin was something like:
```bash
helm upgrade --install some-release --namespace=whatever -f my-values.yaml -f secrets://secrets.yaml chart --version="x.y.z" --dry-run
```

Unfortunately the command terminates with the error message mentioned at the beginning.

### To install the plugin I used:
```bash
helm plugin install https://github.com/jkroepke/helm-secrets --version v3.13.0
```
I even tried the manual way like:
```bash
curl -LsSf https://github.com/jkroepke/helm-secrets/releases/latest/download/helm-secrets.tar.gz | tar -C "/c/Users/MY_USER/AppData/Roaming/helm/plugins" -xzf-
```

In both cases the installation seemed successfull and I could validate the plugin using e.g.:
```bash
$ helm plugin list
NAME    VERSION DESCRIPTION
secrets 3.13.0  This plugin provides secrets values encryption for Helm charts secure storing
```

### Expected Behavior

The plugin would work as expected!

### Environment

- Helm Version: `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}`
- Helm Secrets Version: `3.13.0`
- OS: `Windows`
- Shell: `MINGW`

**Comment by jkroepke** [comment]
Hi,

can you confirm, the environment variable `HELM_SECRETS_WINDOWS_SHELL` is not set?

Can you modify this line

https://github.com/jkroepke/helm-secrets/blob/480331a57eae2458463b7420edbf54bc17abc90e/scripts/wrapper/sh.cmd#L2

to

```cmd
@echo on
```

And re-run helm secrets?

**Comment by sherifkayad** [comment]
@jkroepke the env variable `HELM_SECRETS_WINDOWS_SHELL` is not set .. I could validate that by getting an empty result for `echo $HELM_SECRETS`

After performing the change you suggested, unfortunately the result is exactly the same like before:
```bash
Release "some-release" does not exist. Installing it now.
Error: fork/exec C:\Users\MY_USER\AppData\Roaming\helm\plugins\helm-secrets\scripts\run.sh: %1 is not a valid Win32 application.
```

**Comment by jkroepke** [comment]
Based in the result you provided, it feels like helm does not execute the platformCommand for windows, instead just running the command.

https://github.com/jkroepke/helm-secrets/blob/480331a57eae2458463b7420edbf54bc17abc90e/plugin.yaml#L7-L10

What happens, if you modify the plugin.yaml from

```yaml
command: "$HELM_PLUGIN_DIR/scripts/run.sh" 
platformCommand: 
  - os: windows 
    command: "cmd /c $HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd $HELM_PLUGIN_DIR\\scripts\\run.sh" 
```

to

```yaml
command: "echo linux" 
platformCommand: 
  - os: windows 
    command: "cmd /c echo windows" 
```

And post the output here?

**Comment by sherifkayad** [comment]
also same result .. I believe the issue is in the downloader part .. when I changed the downloader to:
```yaml
downloaders:
  - command: "echo downloader"
```

I got a different error as follows:
```bash
Release "some-release" does not exist. Installing it now.
Error: exec: "C:\\Users\\MY_USER\\AppData\\Roaming\\helm\\plugins\\helm-secrets\\echo": file does not exist
```

**Comment by sherifkayad** [comment]
@jkroepke any idea?

**Comment by jkroepke** [comment]
Using the wrapper instead the scheme based approach should work for you here.
```bash
helm secrets upgrade --install some-release --namespace=whatever -f my-values.yaml -f secrets.yaml chart --version="x.y.z" --dry-run
```

Something like 
```
downloaders:
  - command: "$HELM_PLUGIN_DIR/scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/run.sh"
```

could be an alternative.

**Comment by sherifkayad** [comment]
Unfortunately neither the wrapper nor the change in the downloaders worked for me!

Could that be related that my userfolder is containing a space? e.g. `My User`

**Comment by sherifkayad** [comment]
@jkroepke I came across the comment here https://github.com/zendesk/helm-secrets/issues/114#issuecomment-585021122 .. should I try that or is that a very old issue that now should be working fine in your updated fork of the project?

**Comment by jkroepke** [comment]
> Error: exec: "C:\\Users\\My User\\AppData\\Roaming\\helm\\plugins\\helm-secrets\\$HELM_PLUGIN_DIR\\scripts\\wrapper\\run.cmd": file does not exist

Try

```
downloaders:
  - command: "scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/run.sh"
```

> Could that be related that my userfolder is containing a space? e.g. My User
Yes, but this is an error on our side.

**Comment by sherifkayad** [comment]
> > Error: exec: "C:\Users\My User\AppData\Roaming\helm\plugins\helm-secrets\$HELM_PLUGIN_DIR\scripts\wrapper\run.cmd": file does not exist
> 
> Try
> 
> ```
> downloaders:
>   - command: "scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/run.sh"
> ```

Trying that gave me:
- Using protocol e.g. `-f secrets://secrets.yaml`
```
'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "scripts/wrapper/run.cmd $HELM_PLUGIN_DIR/scripts/run.sh" exited with error
```

- Using wrapper `helm secrets upgrade`:
```
'C:\Users\My' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "secrets" exited with error
```

**Comment by sherifkayad** [comment]
with `@echo on` in both the `sh.cmd` and `run.cmd` I didn't get any additional info. Exactly like above.

**Comment by jkroepke** [comment]
Sorry, I'm currently on a Mac. Reading https://stackoverflow.com/questions/6376113/how-do-i-use-spaces-in-the-command-prompt could help 

```
platformCommand: 
  - os: windows 
    command: "cmd /c "$HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd" $HELM_PLUGIN_DIR\\scripts\\run.sh" 
```

**Comment by jkroepke** [comment]
Whats wrong with first?

**Comment by sherifkayad** [comment]
has double backward slashes `\\` e.g.:
```
'\"C:\Users\My User\AppData\Roaming\helm\plugins\helm-secrets\\scripts\\wrapper\\sh.cmd"' is not recognized as an internal or external command,
operable program or batch file.
Error: plugin "secrets" exited with error
```

**Comment by jkroepke** [comment]
What about

```
platformCommand:
  - os: windows
    command: 'cmd /c "$HELM_PLUGIN_DIR/scripts/wrapper/sh.cmd" "$HELM_PLUGIN_DIR/scripts/run.sh"'
```

```
platformCommand:
  - os: windows
    command: 'cmd /c "$HELM_PLUGIN_DIR\scripts\wrapper\sh.cmd" "$HELM_PLUGIN_DIR\scripts\run.sh"'
```

```
platformCommand:
  - os: windows
    command: >-
      cmd /c "$HELM_PLUGIN_DIR/scripts/wrapper/sh.cmd" "$HELM_PLUGIN_DIR/scripts/run.sh"
```

```
platformCommand:
  - os: windows
    command: >-
      cmd /c "$HELM_PLUGIN_DIR\\scripts\\wrapper\\sh.cmd" "$HELM_PLUGIN_DIR\\scripts\\run.sh"
```

```
platformCommand:
  - os: windows
    command: >-
      cmd /c "$HELM_PLUGIN_DIR\scripts\wrapper\sh.cmd" "$HELM_PLUGIN_DIR\scripts\run.sh"
```
