### ISSUE TITLE
Problem with default HELM_SECRETS_DEC_SUFFIX and gotmpl files

### ISSUE THREAD

**Issue by andrey-gava** [jkroepke/helm-secrets#248]
### Current Behavior

Helmfile:
```
  ocp-production:
    values:
      - ../environments/ocp-prod/common.yaml.gotmpl
    secrets:
      - ../environments/ocp-prod/shared-secrets-encrypted.yaml.gotmpl
```

After execute I get error:
```
Decrypting secret /home/user/sops/platform-production.39/environments/ocp-prod/shared-secrets-encrypted.yaml.gotmpl
open /home/user/sops/platform-production.39/environments/ocp-prod/shared-secrets-encrypted.yaml.gotmpl.yaml.dec: no such file or directory
open /home/user/sops/platform-production.39/environments/ocp-prod/shared-secrets-encrypted.yaml.gotmpl.yaml.dec: no such file or directory
in helmfile/helmfile-shared.yaml: failed to read helmfile-shared.yaml: failed loading environment secrets with 1 errors
```

File list in folder:
```
common.yaml.gotmpl
shared-secrets-encrypted.yaml.gotmpl
shared-secrets-encrypted.yaml.gotmpl.dec
```

You may notice that file name is shared-secrets-encrypted.**yaml.gotmpl.dec** but helmfile/helmsecret for some reason search for  shared-secrets-encrypted.**yaml.gotmpl.yaml.dec**

If I export HELM_SECRETS_DEC_SUFFIX=".yaml.gotmpl.dec". Which I think is bad idea.
Then template cant be done because map has no entry for key "name_of_the_key_here"
I think that because helmfile cant read the keys/values from file that begging with `data: |-`

### Environment

- Helm Version: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
- Helm Secrets Version: 3.15.0
- Helmfile: 0.145.2
- OS: Debian 11
- Shell: bash
