### ISSUE TITLE
Documentation about using with Helm's `--set-file` through ArgoCD's transposed `fileParameters`

### ISSUE THREAD

**Issue by almereyda** [jkroepke/helm-secrets#254]
### Problem Statement

ArgoCD supports setting Helm file parameters through a key `fileParameters` in an application manifest.

- https://github.com/argoproj/argo-cd/pull/2752

Recently #252 was merged, which brings support for `--set-file` to `helm-secrets`.

Is there a known way to use this together with ArgoCD applications?

### Proposed Solution

A step-by-step tutorial exists which explains how to set up `helm-secrets` within ArgoCD `fileParameters`.

### Environment

- Helm Version: ArgoCD v2.4.0
- Helm Secrets Version: 3.15.0

**Comment by almereyda** [comment]
This feature is used in https://github.com/mmz-srf/passbolt-helm, for example.

**Comment by jkroepke** [comment]
To use, `--set-file`, helm secrets needs to be called in wrapper mode through `helm secrets upgrade -f secrets.yaml`. The current ArgoCD Integration currently documents only the downloader mode, e.g. `helm upgrade -f secrets://`.

**Comment by jkroepke** [comment]
@almereyda 

Could you try this?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  source:
    helm:
      fileParameters:
        - name: config
          path: secrets://secrets.yaml
```

Seems like the downloader syntax is supported on --file-set, too.

**Comment by almereyda** [comment]
While this syntax works perfectly for unaltered files, it leaves the Sops-encrypted files intact:

```shell
$ k get secrets passbolt-passbolt-helm-jwt -o yaml | yq '.data."jwt.key"' | base64 -d | jq 'keys'
[
  "data",
  "sops"
]
$ k get secrets passbolt-passbolt-helm-jwt -o yaml | yq '.data."jwt.pem"' | base64 -d | rg '^-'
-----BEGIN PUBLIC KEY-----
-----END PUBLIC KEY-----
$ k get secrets passbolt-passbolt-helm-gpg -o yaml | yq '.data."serverkey.asc"' | base64 -d | rg '^-' 
-----BEGIN PGP PUBLIC KEY BLOCK-----
-----END PGP PUBLIC KEY BLOCK-----
$ k get secrets passbolt-passbolt-helm-gpg -o yaml | yq '.data."serverkey_private.asc"' | base64 -d | jq 'keys'
[
  "data",
  "sops"
]
```

With reference from the application manifest:

```yaml
spec:
  helm:
    source:
      valueFiles:
        - values.yaml
        - secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?secrets.yaml
      fileParameters:
        - name: passbolt.config.serverkey
          path: ./secrets/gpg/serverkey.asc
        - name: passbolt.config.serverkey_private
          path: secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?./secrets/gpg/serverkey_private.asc
        - name: passbolt.config.jwtkey
          path: secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#key.txt?./secrets/jwt/jwt.key
        - name: passbolt.config.jwtcert
          path: ./secrets/jwt/jwt.pem
```

It also doesn't work if I leave out `./` before the paths of the encrypted files.
