### ISSUE TITLE
ArgoCD with helm-secrets

### ISSUE THREAD

**Issue by ldacey** [jkroepke/helm-secrets#262]
### Current Behavior

My secrets are not being read from my Gitlab repo. I feel like I am close to getting this to work, but after a lot of testing I was not successful.

This ApplicationSet correctly reads each folder, creates a namespace, and deploys the services using the custom values.yaml.

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
spec:
  generators:
  - git:
      repoURL: https://gitlab.com/airflow.git
      revision: HEAD
      directories:
        - path: applications/charts/*
  template:
    metadata:
      name: '{{ path.basename }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://gitlab.com/airflow.git
        targetRevision: HEAD
        path: '{{ path }}'
        helm:
          valueFiles:
            - values.yaml
            - secrets://secrets.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=false
```

Each app looks like this. The secrets.yaml file is encrypted with Google KMS. Local encryption/decryption works fine with helm secrets.

```
charts/
  jupyter/
     Chart.yaml
     secrets.yaml
     values.yaml
  airflow/
     Chart.yaml
     secrets.yaml
     values.yaml
```

Example Chart.yaml:

```
apiVersion: v2
name: daskhub
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: daskhub
    version: 2022.8.2
    repository: https://helm.dask.org/
```

When I exec into the pod, I can see that helm secrets was installed correctly. The argo-cd-repo-server is a custom Docker image using the example posted in the guide.

```
kubectl exec -it argo-cd-argocd-repo-server-5b5 -c repo-server -n argocd -- /bin/bash

printenv
HELM_SECRETS_VERSION=3.14.1
SOPS_VERSION=3.7.3
HELM_PLUGINS=/home/argocd/.local/share/helm/plugins/
HELM_DATA_HOME=/helm-working-dir
```

Snapshot of my values.yaml for ArgoCD as well, which covers the serviceaccount and FileSchemes.

```
  repoServer:
    name: repo-server
    replicas: 1
    image:
      repository: registry.gitlab.com/argocd
      tag: latest
      pullPolicy: Always
    serviceAccount:
      create: true
      name: "argocd-repo-server"
      annotations:
        iam.gke.io/gcp-service-account: "gke-cluster-admin@project-id.iam.gserviceaccount.com"
      automountServiceAccountToken: true

  server:
    configEnabled: true
    service:
      type: LoadBalancer
    config:
      helm.valuesFileSchemes: >-
        secrets+gpg-import, secrets+gpg-import-kubernetes,
        secrets+age-import, secrets+age-import-kubernetes,
        secrets,
        https
```

Is there anyway to check from the pod if I can connect to the secrets or read them? I am not sure why values.yaml works fine.

### Environment

- Helm Version: v3.8.1
- Helm Secrets Version: 3.14.1
- OS: Ubuntu 22.04.1 LTS
- Shell: bash

**Comment by jkroepke** [comment]
Did you receive any errors?

Are you using sops? If yes, how do you define your encryption key?

**Comment by ldacey** [comment]
I tried adding a link to the specific raw file and I did run into an error in ArgoCD (apps would not sync at all) which makes me think `secrets://secrets.yaml` is fine. 

`secrets://https://gitlab.com/group/airflow/-/raw/main/applications/charts/{{ path.basename }}/secrets.yaml`

When I check the K8s logs for argocd-repo-server, I do see some errors:

```

{
  "textPayload": "time=\"2022-09-09T13:58:14Z\" level=info msg=\"manifest cache hit: &ApplicationSource{RepoURL:https://gitlab.com/group/airflow.git,Path:applications/charts/jupyter,TargetRevision:HEAD,Helm:nil,Kustomize:nil,Directory:nil,Plugin:nil,Chart:,}/f187f8444f9cfe77ee14bc51e6c169610958d842\"",
  "severity": "ERROR",
  "labels": {a
    "k8s-pod/app_kubernetes_io/name": "argocd-repo-server",
    "k8s-pod/helm_sh/chart": "argo-cd-5.4.1",
  },
}
```

I am using sops, and I have a .sops.yaml file in my applications folder.

```
creation_rules:
   - gcp_kms: projects/project-id/locations/global/keyRings/cluster-sops-keyring/cryptoKeys/key-name
     encrypted_regex: '^(data|stringData)$'
```

Running helm secrets enc locally encrypts the data and respects the encrypted_regex rules, so it is finding .sops.yaml file. Note that this fill is in the root applications folder next to my applicationset file, do I need to add it to my individual services folders?

```
applications/
   charts/
       airflow/
           Chart.yaml
           secrets.yaml
           values.yaml
   .sops.yaml
   applicationset.yaml
```

FYI, I just tested removing secrets.yaml from one of my service folders. ArgoCD failed to sync and this was in the log which tells me that it must be finding the secrets.yaml normally, but it is not creating the secrets. I feel like I am so close.. I must be making some small mistake.

`failed exit status 2: [helm-secrets] File does not exist: secrets.yaml panic: runtime`

Is there anything I can test?

**Comment by jkroepke** [comment]
the easiest way to test this is to open a shell on the repo-server, clone your git and run 

`helm template . -f secrets://secrets.yaml`

**Comment by ldacey** [comment]
So I entered the repo-server pod and cloned my repository. I had to use `helm dependency update` and then I ran the helm template command which seemed to work, but I could not find any reference to the actual secrets.yaml file. I can see references from values.yaml, but not secrets.yaml.

```
git clone
cd applications/chart/jupyter
helm dependency update
argocd@argo-cd-argocd-repo-server: ~/airflow/applications/charts/jupyter$ helm template . -f secrets://secrets.yaml  | grep gitlab
    _PROPERTIES = json.loads("{\"gateway\":{\"affinity\":{},\"annotations\":{},\"auth\":{\"custom\":{\"config\":{}},\"jupyterhub\":{},\"kerberos\":{},\"simple\":{},\"type\":\"jupyterhub\"},\"backend\":{\"environment\":{},\"image\":{\"name\":\"ghcr.io/dask/dask-gateway\",\"pullPolicy\":\"IfNotPresent\",\"tag\":\"2022.6.1\"},\"scheduler\":{\"cores\":{},\"extraContainerConfig\":{},\"extraPodConfig\":{},\"memory\":{}},\"worker\":{\"cores\":{},\"extraContainerConfig\":{},\"extraPodConfig\":{},\"memory\":{}}},\"image\":{\"name\":\"registry.gitlab.com/project/jupyterhub\",\"pullPolicy\":\"Always\",\"tag\":\"latest\"},\"imagePullSecrets\":[{\"name\":\"gitlab-registry\"}],\"livenessProbe\":{\"enabled\":true,\"failureThreshold\":6,\"initialDelaySeconds\":5,\"periodSeconds\":10,\"timeoutSeconds\":2},\"loglevel\":\"INFO\",\"nodeSelector\":{},\"prefix\":\"/services/dask-gateway\",\"readinessProbe\":{\"enabled\":true,\"failureThreshold\":3,\"initialDelaySeconds\":5,\"periodSeconds\":10,\"timeoutSeconds\":2},\"replicas\":1,\"resources\":{},\"service\":{\"annotations\":{}},\"tolerations\":[]}}")
        String("image", default="registry.gitlab.com/project/jupyterhub:latest", label="Image"),
      imagePullSecrets: [{"name":"gitlab-registry"}]
          image: registry.gitlab.com/project/jupyterhub:latest
        - name: gitlab-registry
          image: registry.gitlab.com/project/jupyterhub:latest
      imagePullSecrets: [{"name":"gitlab-registry"}]
          image: registry.gitlab.com/project/jupyterhub:latest
```


Here is the secrets.yaml file I have in that folder (modified slightly):

```
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:---,tag:---,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-registry
    namespace: jupyter
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/airflow/locations/global/keyRings/cluster-sops-keyring/cryptoKeys/name
          created_at: "2022-09-08T13:39:58Z"
          enc: ---
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-08T13:39:59Z"
    mac: ENC[AES256_GCM,data:---,tag:---,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
```
