### ISSUE TITLE
Add support for ArgoCD's `ignoreMissingValueFile`

### ISSUE THREAD

**Issue by arielweinberger** [jkroepke/helm-secrets#276]
### Problem Statement

ArgoCD supports a `ignoreMissingValueFiles` in its Application/ApplicationSet definitions. For example:

```yaml
...
  template:
    metadata:
      name: '{{name}}-{{envName}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: default
      source:
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - path-to-file-1.yaml
          - path-to-file-2.yaml
```

This is extremely useful, especially in ApplicationSet, where ops teams set up environments in a multi-env/multi-tenant setup.

This is currently not supported by helm-secrets. Putting a `secrets://path-to-file.yaml` there results in an error if the file does not exist:
```
failed exit status 2: [helm-secrets] File does not exist: file-does-not-exist.yaml panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1814558] goroutine 1 [running]: bytes.(*Buffer).Bytes(...) bytes/buffer.go:54 helm.sh/helm/v3/pkg/cli/values.readFile({0xc0003d1a10, 0x100000000000007}, {0xc0000cac00, 0x3, 0x4}) helm.sh/helm/v3/pkg/cli/values/options.go:120 +0x138 helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc00053ecc0, {0xc0000cac00, 0xc00069f9f8, 0xc000585540}) helm.sh/helm/v3/pkg/cli/values/options.go:48 +0x385 main.runInstall({0xc0002c1300, 0x214, 0xc00069fac0}, 0xc0000f2b00, 0x2000, {0x1f68cc0, 0xc00000e018}) helm.sh/helm/v3/cmd/helm/install.go:198 +0x385 main.newTemplateCmd.func2(0xc000463680, {0xc0002c1300, 0x1, 0x10c}) helm.sh/helm/v3/cmd/helm/template.go:82 +0x22a github.com/spf13/cobra.(*Command).execute(0xc000463680, {0xc0002c0000, 0x10c, 0x130}) github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ed400) github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.3.0/command.go:902 main.main() helm.sh/helm/v3/cmd/helm/helm.go:83 +0x234
```

### Proposed Solution

It would be great to add support for this feature. What I propose is to check if `ignoreMissingValueFiles` equals `true`, and if so, allow the secrets import to fail if it's a "file not found" error.

### Environment

- Helm Secrets Version: v4.0.0
- Shell: zsh
- ArgoCD: v2.4.7
