### ISSUE TITLE
ArgoCD integration - missing doc info + strange/incorrect secret file location?

### ISSUE THREAD

**Issue by cr1st1p** [jkroepke/helm-secrets#294]
### Problem Statement

Documentation is missing a very important point, for integration into ArgoCD and sops+age for example, when using file urls like 
secrets+gpg-import:///helm-secrets-private-keys/key.asc?secrets.yaml
In which directory is 'secrets.yaml' supposed to be?

My expectation is that it should be in the same directory structure as the ArgoCD Application file loading the chart:
Chart.yaml
templates/
  - app.yaml (kind: Application; argoproj.io/v1alpha1)
     - which loads an EXTERNAL chart, lets's say 'app1'. Chart NOT maintained by me (think Prometheus, mysql, whatever)
     - which uses a reference to secrets.yaml (secrets+age-import: ...)
     - has a key source.helm.values - with things to tailor 'app1'
  - app2.yaml (similar)
  - app3.yaml (similar)
secrets.yaml <---- this

But that does not look to work - I'm getting a secrets.yaml file not found;  (+ a segfault, but let's assume Helm is buggy)

By checking your demo in https://github.com/jkroepke/helm-secrets/tree/main/examples it looks like the secrets.yaml file should be inside the *final* app chart being installed, in your case 'examples/sops', in example above, in app1's chart !??
Either I'm missing something but this is totally unexpected - I would expect to have the secrets somewhere near the place that defines the values to use for calling the external helm chart and not *inside* the final apps' chart. Similar to how I'm adding in app.yaml (from my directory layout above) an entry source.helm.values

Can you please clarify?
Thank you!

### Environment

- Helm Version: 3.8.1 (inside argo-repo-server)
- Helm Secrets Version: 4.2.2 (as downloaded by the argo-repo-server init container)
- OS: Linux
- Shell:

**Comment by jkroepke** [comment]
Hi @cr1st1p,

I wrote the documentation with the background that helm-secrets is still helm plugin. The secret files must be passed to the helm call. The ArgoCD integration covers additional features and QOL mechanism of helm-secrets, but from ArgoCD perspective, everything is done inside the Application itself. Each Application is a dedicated context. By default, only the applications git directory is available inside argocd-repo-server 

Initially, only secret files inside the helm charts are supported. 

external secrets (outside the application helm chart) are possible through multiple mechnaics, but all mechanics are a bit hacky unless [multiple-sources-for-applications](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/multiple-sources-for-applications.md) are available.

1. pass [additional remote valueFiles](https://github.com/jkroepke/helm-secrets/wiki/Values#remote-values-from-git)
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  source:
    helm:
      valueFiles:
        - secrets://https://raw.githubusercontent.com/org/repo/ref/pathtofile.yml
        - secrets://git+https://github.com/jkroepke/helm-secrets@tests/assets/values/sops/secrets.yaml?ref=main # requires helm-git
```

2. pass inline secrets through file with [vals backend](https://github.com/jkroepke/helm-secrets/wiki/Secret-Backends#vals)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  source:
    helm:
      fileParameters:
        - name: mysql.rootPassword
          path: secrets+literal://ref+vault://secret/mysql#/rootPassword
```
