### ISSUE TITLE
Add support for multi-source ArgoCD applications

### ISSUE THREAD

**Issue by jeroen-s** [jkroepke/helm-secrets#316]
### Problem Statement

ArgoCD 2.6.0-RC1 finally introduced multi-source applications. It would be great if `helm-secrets` also supported this feature.

### Proposed Solution

For the end user it might look something like:

```
spec:
  sources:
    - repoURL: git@github.com:my/repo.git
      targetRevision: main
      ref: values
    - repoURL: https://my-repo.github.io/helm-charts
      chart: my-chart
      targetRevision: 1.0
      helm:
        valueFiles:
          - $values/some-path/values.yaml
          - secrets://$values/some-path/secrets.yaml
```

### Environment

- ArgoCD Version: 2.6.0-RC1
- Helm Secrets Version: 3.12.0
