### ISSUE TITLE
Question: Unable to use both sops and Vals backend in ArgoCD... intended?

### ISSUE THREAD

**Issue by aztechian** [jkroepke/helm-secrets#317]
### Problem Statement

I had read through the docs/code/examples, and I hadn't come across anything (I _think_) that prevented the use of both/either backends in an ArgoCD configuration. In my testing, it appears though that only one backend can be in use at a time.
When I give the repo-server an environment variable of `HELM_SECRETS_BACKEND=vals` I can use vals backends successfully (in my case AWS Secretsmanager). However, I then can't deploy some other apps using SOPS secrets files. When using `HELM_SECRETS_BACKEND=sops` (or unset) the reverse works - I can use SOPS secret files successfully, but the secrets manager strings are returned unprocessed.

I would have thought that the downloader protocol specification string would have been enough to determine the backend? maybe that's a false assumption?

My use case - I'm transitioning my cluster to the latest Argo CD release and wanting to get away from a custom image that wrapped the helm command with a SOPS decryption ([camptocamp/docker-argocd](https://github.com/camptocamp/docker-argocd)), as it will always be behind and there's now ways to inject tools at runtime. I would like to eventually end up using secrets manager, but was hoping to not have to cut over my entire cluster all at once. Thus, I was hoping to have some argo apps use SOPS, and others Vals.
Thanks for this tool, it fits the bill well for what I'm looking for!

Tangential question: I was never able to find anything that described the differences between the protocol strings `secrets://` and `secrets+literal://`, and when to use them. Have I missed that somewhere?

### Proposed Solution

- helm-secrets can auto-determine the backend per application when using protocol specifiers in ArgoCD

### Environment

- Helm Version: 3.10.3 (bundled with Argo CD 2.5.5)
- Helm Secrets Version: 4.2.2
- OS: Linux, ArgoCD docker image
- Shell: N/A

### Acceptance Criteria

- [ ] As a user, I am able to utilize any backend via the protocol specifier
- [ ] Using the environment variable `HELM_SECRETS_BACKEND` could prevent inadvertent usage of the "other" backend
   * for example `HELM_SECRETS_BACKEND=vals` would "lock" helm secrets to _only_ vals backends, thus preventing **sops** backend usage if so desired by the cluster operator.

**Comment by jkroepke** [comment]
A current workaround would be the sops backend in vals, e.g. `ref+sops://path/to/file#/foo/bar`

https://github.com/variantdev/vals

**Comment by aztechian** [comment]
Thanks @jkroepke , I had not made it around to that option (vals with sops). I was able to get that to work, but I ran into issues getting the gpg private key added into Argo’s custom keychain. It doesn’t appear doable from an init container, unfortunately (not your problem, I know) and requires manual intervention to set up. 
i do appreciate how helm-secrets is able to do that dynamically!

no problem on not implementing the enhancement suggestion - I was just following my question to a possible conclusion. 
thanks for the help. If you want to point me at the docs page you think it would go I can submit a pr to add the secret vs literal bit.

**Comment by jkroepke** [comment]
@aztechian could you take a look at #321?

You can install this PR with `helm plugin install https://github.com/jkroepke/helm-secrets --version multiple-backends`.

The syntax is `<backend>!filepath`, e.g.:

* `secrets://sops!secrets.yaml`
* `secrets://vals!secrets.yaml`

**Comment by aztechian** [comment]
It works!
This is really nice :) 
I deployed my production argo config to Minikube (using your `multiple-backends` branch). This setup was previously only able to use the sops backend (and, in fact still has `HELM_SECRETS_BACKEND=sops` env var).
I then deployed this argo app:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.20
    helm:
      releaseName: webtest
      parameters:
        - name: cloneStaticSiteFromGit.enabled
          value: "true"
        - name: cloneStaticSiteFromGit.repository
          value: https://github.com/schoolofdevops/html-sample-app.git
        - name: cloneStaticSiteFromGit.branch
          value: master
        - name: cloneStaticSiteFromGit.interval
          value: "8000"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hostname
          value: "mysite.127.0.0.1.nip.io"
        - name: service.type
          value: ClusterIP
        - name: service.externalTrafficPolicy
          value: Local
      fileParameters:
        - name: commonLabels.secret
          path: secrets+literal://vals!ref+awssecrets://test/nginx#/testsecret
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

And it just worked. Note, I'm using `secrets+literal` but it did still work. I'd like to try poking around in my use cases a bit more, and see if I can find any edges - but this is great! much appreciated.
