### ISSUE TITLE
Support for referenced valueFiles in multiple sources ArgoCD applications

### ISSUE THREAD

**Issue by almereyda** [jkroepke/helm-secrets#319]
### Problem Statement

When using the new ArgoCD multiple sources applications https://github.com/argoproj/argo-cd/pull/10432, one can reference (`ref: source1`) one source within e.g. the `valueFiles` of another with a shorthand flag `$source1/values.yaml`.

This notation is currently not supported by Helm Secrets.

### Proposed Solution

Helm Secrets also works in multiple sources applications, in so that I can do:

```yaml
  sources:
    - repoURL: https://github.com/example/secrets
      targetRevision: main
      ref: source
    - helm:
        valueFiles:
        - $source/values.yaml
        - secrets+age-import-kubernetes://argocd/sops-age#key?$source/secrets.yaml
      repoURL: https://github.com/example/chart
      targetRevision: main
      path: ./
```

This would also help to work around the limitations expressed in https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#external-chart-and-local-values

Would such behaviour be welcomed by the maintainers here?

### Environment

N/A
