### ISSUE TITLE
Not able to refer awssecrets when using Remote Helm chart with Argo integration

### ISSUE THREAD

**Issue by mdfaizsiddiqui** [jkroepke/helm-secrets#325]
### Current Behavior

With remote helm chart I am not able to refer the secret from AWS secret manager, this is my Argo Application -

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: actions-runner-system
    server: https://kubernetes.default.svc
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: "0.21.x"
    helm:
      releaseName: actions-runner-controller
      fileParameters:
        - name: 'authSecret.github_token'
          path: secrets+literal://ref+awssecrets://github-actions/token?region=us-east-1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
```

This is the output I see -

```
➜  ~ kubectl get secrets/controller-manager -n actions-runner-system --template={{.data.github_token}}  | base64 -D; echo
ref+awssecrets://github-actions/token?region=us-east-1
➜  ~
```

The same thing is working when I have local downloaded copy of the chart -

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: actions-runner-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/<my-org>/<my-repo>.git'
    targetRevision: main
    path: actions-runner-controller
    helm:
      releaseName: actions-runner-controller
      fileParameters:
        - name: 'authSecret.github_token'
          path: secrets+literal://ref+awssecrets://github-actions/token?region=us-east-1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
```

### Expected Behavior

Output for below command should return the secret stored in AWS Secret Manager -

```
➜  ~ kubectl get secrets/controller-manager -n actions-runner-system --template={{.data.github_token}}  | base64 -D; echo
```

### Environment

- Helm Version: v3.10.3
- Helm Secrets Version: 4.2.2
- Vals Version: 0.21.0
- ArgoCD Version: v2.5.7+e0ee345
- OS:
- Shell:
