### ISSUE TITLE
Secret is appearing as null

### ISSUE THREAD

**Issue by amirza-clear** [jkroepke/helm-secrets#333]
### Current Behavior

Followed instructions to a tee for argocd integreation. Using the init container and Im able to locally decrypt my files. My app is deploying just fine but under the secret the value is appearing as null. I uncommented the wrapper items from the init container values file as shown as wiki thinking that should dynamically decrypt my file.

      {"apiVersion":"v1","data":null,"kind":"Secret","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"test4"},"name":"test4","namespace":"argo"}}
      

shows up as above ^^

Secrets.yaml under template is: 

---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
  {{- range $key,$val := $.Values.secrets}}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}

---
secrets.yaml as such:

secrets:
    secrets: secret

_
my values.yaml has

secrets: {} 

### Expected Behavior

Expecting my value to appear in the secret.  
- have my .sops.yaml with proper permissions in IAM 
- created a secrets.yaml 

### Environment

- ArgoCD Version 2.5.7
HELM_SECRETS_VERSION: "4.2.2"
KUBECTL_VERSION: "1.22"
SOPS_VERSION: "3.7.3"

**Comment by jkroepke** [comment]
Your range loop looks broken. How you call helm?

**Comment by amirza-clear** [comment]
Deploying via argo, just entering secrets://secrets.yaml in the values file under help within the argo gui when creating a new app.

**Comment by amirza-clear** [comment]
testapp/templates/deployment.yaml
`---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
    spec:
      containers:
        - name: "nginx"
          image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: "html"
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 80
      volumes:
        - name: "html"
          secret:
            secretName: {{ $.Release.Name | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name | quote }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  replicas: {{ $.Values.replicaCount }}`


testapp/templates/service.yaml
`---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: {{ $.Chart.Name | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: "http"`

testapp/templates/secrets.yaml
`---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
data:
  {{- range $key,$val := $.Values.secrets}}
    {{ $key }}: {{ $val | b64enc }}
  {{- end }}`

testapp/secrets.yaml
dec secret (ran helm secrets dec secrets.yaml locally)
```
secrets:
    secrets: secret
```
testapp/values.yaml
values.yaml
`---
image:
  repository: "nginx"
  tag: "1.17"
  pullPolicy: "IfNotPresent"

replicaCount: 1

secrets: {}`

testapp/Chart.yaml
chart.yaml:
`---
apiVersion: "v2"
name: "hello-world"
version: 0`

**Comment by jkroepke** [comment]
Can you use code blocks like this?


```yaml
----
hello: world
```

**Comment by amirza-clear** [comment]
----
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
    spec:
      containers:
        - name: "nginx"
          image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: "html"
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 80
      volumes:
        - name: "html"
          secret:
            secretName: {{ $.Release.Name | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name | quote }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  replicas: {{ $.Values.replicaCount }}

**Comment by amirza-clear** [comment]
```yaml
----
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | quote }}
    spec:
      containers:
        - name: "nginx"
          image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: "html"
              mountPath: "/usr/share/nginx/html"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 80
      volumes:
        - name: "html"
          secret:
            secretName: {{ $.Release.Name | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name | quote }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  replicas: {{ $.Values.replicaCount }}

```

**Comment by amirza-clear** [comment]
```
testapp/Charts.yaml
----
apiVersion: "v2"
name: "hello-world"
version: 0
```

```
testapp/values.yaml
---
image:
  repository: "nginx"
  tag: "1.17"
  pullPolicy: "IfNotPresent"

replicaCount: 1

secrets: {}

```

```
testapp/secrets.yaml

secrets:
    secrets: secret
```
