### ISSUE TITLE
ArgoCD Application Helm values not rendering.

### ISSUE THREAD

**Issue by powellchristoph** [jkroepke/helm-secrets#336]
### Current Behavior

I have an `ApplicationSet` to install a helm chart while pulling secrets from `Vault` using `helm-secrets` configured with `vals`. The secret isn't rendered, instead it just includes the path.

The `ApplicationSet`.
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  template:
      source:
        helm:
          releaseName: installed-operator
          values: |
            cloudConfig:
              global:
                region: {{metadata.labels.region}}
                application-credential-id: secrets://ref+vault://path/to/secret/{{metadata.labels.cluster}}/{{metadata.labels.environment}}#/application_credential_id
                application-credential-secret: secrets://ref+vault://path/to/secret/{{metadata.labels.cluster}}/{{metadata.labels.environment}}#/application_credential_secret
```

Which creates the `Application`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  source:
    helm:
      releaseName: installed-operator
      values: |
        cloudConfig:
          global:
            region: use1-prod0-os
            application-credential-id: secrets://ref+vault://path/to/secret/snyk/prod0#/application_credential_id
            application-credential-secret: secrets://ref+vault://path/to/secret/snyk/prod0#/application_credential_secret
```

Which creates the kubernetes secret data as
```
[Global]
region = use1-prod0-os
application-credential-id = secrets://ref+vault://path/to/secret/snyk/prod0#/application_credential_id
application-credential-secret = secrets://ref+vault://path/to/secret/snyk/prod0#/application_credential_secret
```

I am assuming that I am simply not escaping something properly. Also, the `helm` container has `vals` and `helm-secret` installed and configured.

### Expected Behavior

I would like the rendered `Applications` to have the correct secrets.

### Steps To Reproduce

```markdown
Create an ArgoCD `ApplicationSet` as referenced above.
```

### Environment

- Helm Version: 3.10.2
- Helm Secrets Version: 4.2.2
- ArgoCD Version: v2.5.10+d311fad
- OS: 5.4.0-136-generic #153-Ubuntu SMP x86_64 GNU/Linux
- Shell: /bin/bash

**Comment by jkroepke** [comment]
There are 2 ways to decrypt secrets via helm-secret.

https://github.com/jkroepke/helm-secrets#usage

For performance reasons, the documentation of the ArgoCD Integration here prefers the plugin download method. 

The method has some downside, e.g. all secrets files needs to be references with secret:// to get decrypted. This may not compatible with the inline values inside ArgoCD.

To support your use case, I recently implemented support for `--set-file` .

Your use-case could be archived by something like this:

```yaml
      # fileParameters (--set-file) are supported, too. 
      fileParameters:
        - name: cloudConfig.global.application-credential-id
          path: secrets+literal://vals!ref+vault://path/to/secret/{{metadata.labels.cluster}}/{{metadata.labels.environment}}#/application_credential_id
```

Example: https://github.com/jkroepke/homelab/blob/bf967a80068809aa241e301e12f166fe4af114a2/aks/argocd/oauth2-proxy.yaml#L17-L21
