### ISSUE TITLE
ArgoCD: using "secrets://" does not work with values files from external Git repository

### ISSUE THREAD

**Issue by Obirah** [jkroepke/helm-secrets#337]
### Current Behavior

ArgoCD has a [mechanism to reference values files from external git repositories](https://argo-cd.readthedocs.io/en/latest/user-guide/multiple_sources/#helm-value-files-from-external-git-repository). When I try to use helm-secrets with the approach from the example (i.e. specifying `secrets://$values/charts/prometheus/values.yaml` as a valueFile of the App), helm-secrets returns a file not found error.

### Expected Behavior

I would expect helm-secrets to be able to resolve secrets through a values file from an external git repository in the same way as it does from the app's repository.

### Steps To Reproduce
Use an ArgoCD app that looks like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus
    targetRevision: 15.7.1
    helm:
      valueFiles:
      - $values/charts/prometheus/values.yaml
      - secrets://$values/secrets.yaml
  - repoURL: 'https://git.example.gom/org/value-files.git'
    targetRevision: dev
    ref: values
```

With `https://git.example.gom/org/value-files.git` being a git repository that contains the referenced `secrets.yaml` with references to any secrets (in my case AWS secrets manager, but that of course doesn't matter here).

### Environment
- Helm Secrets Version: 4.2.2
- ArgoCD Version: 2.6.2
- OS: k8s 1.24
