### ISSUE TITLE
Remote File 404

### ISSUE THREAD

**Issue by atsai1220** [jkroepke/helm-secrets#347]
### Current Behavior

Currently ArgoCD is displaying this error. I am pretty sure the URL will not expose my token but the 404 seems to indicate that a token is not actually used at all.

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . 
--name-template cluster-template-use1-preprod 
--namespace fleet-default 
--kube-version 1.21 
--values secrets://https://@raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/use1-preprod/secret.yaml 
--values /tmp/4e7ac538-db11-490b-beb1-b17253fdc9d4`

failed exit status 1:
curl: (22) The requested URL returned error: 404
[helm-secrets] Error while download url https://@raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/use1-preprod/secret.yaml
[helm-secrets] File does not exist: https://@raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/use1-preprod/secret.yaml Error: plugin "scripts/run.sh downloader" exited with error
```
<img width="813" alt="Screenshot 2023-02-27 at 7 20 11 PM" src="https://user-images.githubusercontent.com/14171643/221745099-d43b6d49-0849-449c-b714-abf465dea6fe.png">

However, if I curl with the token inside my `deploy/argocd-repo-server` container then everything is as expected.
```
argocd@argocd-repo-server-5c986974f7-jbfqr:~$ echo $GITHUB_TOKEN
400xxxxxxxxxxxxxxxxx

argocd@argocd-repo-server-5c986974f7-jbfqr:~$ curl https://400xxxxxxxxxxxxxxxxx@raw.git.viasat.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/use1-preprod/secret.yaml
<expected output>
```

### Expected Behavior

I expect remote values to be retrieved then decoded with `val` against our Hashicorp Vault backend.

### Steps To Reproduce

This is my Dockerfile. It is the same as described in the wiki [here](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#option-1-custom-docker-image) except I'm not using `HELM_SECRETS_WRAPPER_ENABLED`. **Is that required?** I'm not using a multi-source application.

``` docker
ARG ARGOCD_VERSION="v2.6.2"
FROM argoproj/argocd:$ARGOCD_VERSION
ARG VALS_VERSION="0.22.0"
ARG HELM_SECRETS_VERSION="4.4.0"
ARG KUBECTL_VERSION="1.26.1"

# In case wrapper scripts are used, HELM_SECRETS_HELM_PATH needs to be the path of the real helm binary
ENV HELM_SECRETS_HELM_PATH="/usr/local/bin/helm" \
    HELM_PLUGINS="/home/argocd/.local/share/helm/plugins/" \
    HELM_SECRETS_VALUES_ALLOW_SYMLINKS=true \
    HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH=true \
    HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL=true \
    HELM_SECRETS_BACKEND="vals" \
    HELM_SECRETS_URL_VARIABLE_EXPANSION=true

USER root
RUN apt-get update && \
    apt-get install -y \
    curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -fsSL https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl

# vals driver installation
RUN curl -fsSL https://github.com/variantdev/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz \
    | tar xzf - -C /usr/local/bin/ vals \
    && chmod +x /usr/local/bin/vals

USER 999

RUN helm plugin install --version ${HELM_SECRETS_VERSION} https://github.com/jkroepke/helm-secrets
```

This is my Deployment for `argocd-repo-server`
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - entrypoint.sh
        - argocd-repo-server
        - --redis
        - argocd-redis-ha-haproxy:6379
        env:
        - name: HELM_SECRETS_BACKEND
          value: vals
        - name: HELM_DEBUG
          value: "false"
        - name: HELM_SECRETS_URL_VARIABLE_EXPANSION
          value: "true"
        - name: HELM_SECRETS_IGNORE_MISSING_VALUES
          value: "false"
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
        envFrom:
        - secretRef:
            name: argocd-vault-approle
        image: andrew/argocd-repo-server:v2.6.2-1
        imagePullPolicy: Always
        name: argocd-repo-server
...
      initContainers:
      - command:
        - cp
        - -n
        - /usr/local/bin/argocd
        - /var/run/argocd/argocd-cmp-server
        image: quay.io/argoproj/argocd:v2.6.2
        imagePullPolicy: IfNotPresent
        name: copyutil
...
      volumes:
      - name: vault-ca
        secret:
          defaultMode: 420
          items:
          - key: VAULT_CA
            path: vault-ca
          secretName: argocd-vault-approle
...
```

### Environment

- Helm Version:
```
argocd@argocd-repo-server-5c986974f7-jbfqr:~$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```
- Helm Secrets Version: `4.4.0`
- ArgoCD Version: `v2.6.2`
- OS: Linux
- Shell: Bash

### Anything else?

This is what my ArgoCD application file looks like. I've verified the path is correct by requesting the same URL with a token.
``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-template-use1-preprod
spec:
  project: cluster-templates
  source:
    repoURL: git@git.company.com:OrganizationName/cluster-templates.git
    path: yay
    targetRevision: master
    helm:
      values: |
        foo: bar
      valueFiles:
        - secrets://https://${GITHUB_TOKEN}@raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/sandbox-clusters/use1-preprod/secret.yaml
  destination:
    namespace: fleet-default
    server: https://console.dockyard.somewhere.io/k8s/

```

**Comment by atsai1220** [comment]
If I use a temporary token obtained from the UI then ArgoCD successfully retrieves the file and uses `vals` to integrate with Vault. This makes me think that the problem lies at the earlier stage (before `vals`) of the HTTP get of the remote file.

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-template-usw1-rke2-testing
spec:
  project: cluster-templates
  source:
    repoURL: git@git.viasat.com:OrganizationName/cluster-templates.git
    targetRevision: master
    helm:
      values: |
        foo: bar
      valueFiles:
        - secrets://https://raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/sandbox-clusters/usw1-rke2-testing/secret.yaml?token=GHL123123123123123123123
```

**Comment by atsai1220** [comment]
If I use a temporary token obtained from the UI then ArgoCD **successfully** retrieves the file and uses `vals` to integrate with Vault.

This makes me think that the problem lies at the earlier stage (before `vals`) of the HTTP get of the remote file.

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-template-usw1-rke2-testing
spec:
  project: cluster-templates
  source:
    repoURL: git@git.company.com:OrganizationName/cluster-templates.git
    targetRevision: master
    helm:
      values: |
        foo: bar
      valueFiles:
        - secrets://https://raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/sandbox-clusters/usw1-rke2-testing/secret.yaml?token=GHL123123123123123123123
```

**Comment by jkroepke** [comment]
Can you try this?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-template-use1-preprod
spec:
  project: cluster-templates
  source:
    repoURL: git@git.company.com:OrganizationName/cluster-templates.git
    path: yay
    targetRevision: master
    helm:
      values: |
        foo: bar
      valueFiles:
        - secrets://https://$${GITHUB_TOKEN}@raw.git.company.com/OrganizationName/argocd/master/argocd/apps/cluster-templates/sandbox-clusters/use1-preprod/secret.yaml
  destination:
    namespace: fleet-default
    server: https://console.dockyard.somewhere.io/k8s/
```
