### ISSUE TITLE
Integration with ArgoCD

### ISSUE THREAD

**Issue by nhoangduy1912** [jkroepke/helm-secrets#380]
### Current Behavior

Hi I'm trying to do integration with ArgoCD.

In my environment, I have a helm chart for my application and I encrypted my value file with sops (using age key).

What I want to do is encrypt value file and upload to Git. Then use argocd to decrypt the value file and deploy the application

Here're the steps I took:
1. Use sops and create an age key.
2. Use that age key to encrypt value file.
3. Upload value file to a remote git.
4. Create a secret with the age key.
5. Install argoCD
```
server:
  service:
    type: NodePort

repoServer:
  serviceAccount:
    create: true
    name: argocd-repo-server

  rbac:
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - get
        
  env:
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /custom-tools/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_BACKEND
      value: sops
    # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm

  volumes:
    - name: custom-tools
      emptyDir: {}
    # kubectl create secret generic helm-secrets-private-keys --from-file=key.asc=assets/gpg/private2.gpg
    - name: helm-secrets-private-keys
      secret:
        secretName: helm-secrets-private-keys
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: custom-tools
    - mountPath: /helm-secrets-private-keys/
      name: helm-secrets-private-keys
  initContainers:
    - name: download-tools
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [sh, -ec]
      env:
        - name: HELM_SECRETS_VERSION
          value: "4.4.2"
        - name: KUBECTL_VERSION
          value: "1.26.1"
        - name: VALS_VERSION
          value: "0.24.0"
        - name: SOPS_VERSION
          value: "3.7.3"
      args:
        - |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;
          
          wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

          wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;

          cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm
          
          chmod +x /custom-tools/*
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
```

6. Create application
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-enc
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=app:latest
    argocd-image-updater.argoproj.io/app.force-update: "true"
    argocd-image-updater.argoproj.io/app.update-strategy: digest
spec:
  project: app
  source:
    helm:
      valueFiles:
        - secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#keys.txt?value-enc.yaml
    repoURL: https://gitlab.com/app.git
    targetRevision: main
    path: helm-chart/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
```

Error: 
```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template app-enc --namespace app --kube-version 1.24 --values secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#keys.txt?value-enc.yaml 

failed exit status 1: [helm-secrets] File does not exist: value-enc.yaml Error: failed parsing --set-file data: plugin "scripts/run.sh downloader" exited with error [helm-secrets] helm template command errored on value 'secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#keys.txt?value-enc.yaml' [helm-secrets] File does not exist: secrets+age-import-kubernetes://argocd/helm-secrets-private-keys#keys.txt?value-enc.yaml Error: plugin "secrets" exited with error```


### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

- Helm Version: Helm 3
- Helm Secrets Version: 4.4.2
- ArgoCD Version: 2.7.3



### Anything else?

_No response_
