### ISSUE TITLE
Create kubernetes object from helm encrypted with helm secrets in ArgoCD

### ISSUE THREAD

**Issue by adadeeeh** [jkroepke/helm-secrets#396]
### Current Behavior

I'm trying to create kubernetes secrets from helm that is encrypted with helm secrets in ArgoCD. But kubernetes secrets is not created.

ArgoCD install with Helm using this values:
```
repoServer:
  serviceAccount:
    create: true
    name: "argocd-repo-server"
    annotations:
      iam.gke.io/gcp-service-account: <sa>
    automountServiceAccountToken: true
  env:
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /custom-tools/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_BACKEND
      value: sops
    # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
      value: "true"
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm

    # - name: HELM_SECRETS_LOAD_GPG_KEYS
    #   # Multiple keys can be separated by space
    #   value: /helm-secrets-private-keys/key.asc
  volumes:
    - name: custom-tools
      emptyDir: {}
    # # kubectl create secret generic helm-secrets-private-keys --from-file=key.asc=assets/gpg/private2.gpg
    # - name: helm-secrets-private-keys
    #   secret:
    #     secretName: helm-secrets-private-keys
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: custom-tools
    # - mountPath: /helm-secrets-private-keys/
    #   name: helm-secrets-private-keys
  initContainers:
    - name: download-tools
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [sh, -ec]
      env:
        - name: HELM_SECRETS_VERSION
          value: "4.5.0"
        - name: KUBECTL_VERSION
          value: "1.26.1"
        - name: VALS_VERSION
          value: "0.24.0"
        - name: SOPS_VERSION
          value: "3.7.3"
      args:
        - |
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

          wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
          wget -qO /custom-tools/sops https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux
          wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

          wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;

          cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm

          chmod +x /custom-tools/*
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

configs:
  params:
    server.insecure: true
  cm:
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets,secrets+literal,
      https

```

The helm chart look like this:
```
my-chart
    templates
        secrets.dev.yaml
    .helmignore
    .sops.yaml
    Chart.yaml
```

`secrets.dev.yaml` more or less look like this, I'm using GCP KMS:
```
apiVersion: v1
kind: Secret
metadata:
    name: ms-banner-poc
type: Opaque
stringData:
    some_key: encrypted_value
    sops:
    bla-bla-bla
    pgp: []
    encrypted_regex: stringData
    version: 3.7.3

```

`.helmignore` contains `secrets.dev.yaml`

The ArgoCD application manifest look like this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-only
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/some_repo.git
    targetRevision: HEAD
    path: charts/secrets-only
    helm:
      valueFiles:
        - secrets://templates/secrets.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: some_namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - CreateNamespace=true

```

### Expected Behavior

Kubernetes object that encrypted with helm secrets created

### Environment

- Helm Version: 3.10.2
- Helm Secrets Version: 4.1.1
- ArgoCD Version: 2.8.2
- OS: Container-Optimized OS from Google 
- Shell: bash
