### ISSUE TITLE
Resolving multiple values creates invalid resources

### ISSUE THREAD

**Issue by cromega** [jkroepke/helm-secrets#434]
### Current Behavior

When I have the following template:

```
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData: ref+awsssm://test
```
With a value in Parameter Store in YAML format:

```
value1: secret
value2: secret
```

I get the following rendered secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData: |-
  value1: secret
  value2: secret
```

Is there a way I can extract multiple keys from a single stored parameter and render them as a map as opposed to a string?

### Environment

- Helm Version: 3.12
- Helm Secrets Version: 4.5.1
- ArgoCD Version
- OS: Linux Mint x86_64
- Shell: zsh
