### ISSUE TITLE
Unable to pull multiple in-line secrets from SecretsManager via helmfile

### ISSUE THREAD

**Issue by Kellen275** [jkroepke/helm-secrets#449]
### Current Behavior

I'm attempting to pull secrets from AWS SecretsManager using helmfile.

I'm having trouble when pulling multiple secrets in, specifically, the same line of yaml.

In my helmfile environment values I have
```yaml
secret1: ref+awssecrets://database#/user
secret2: ref+awssecrets://database#/pass
```
In my helmfile release values I'm pulling these in like
```yaml
userPass: { .Values.secret1 }ZZZ{ .Values.secret2 }
```

The issue I'm seeing is that the final rendered yaml is
```yaml
userPass: awssecrets://database#/pass
```
as opposed to
```yaml
userPass: usernameZZZmysecretpassword
```

However if I split it onto multiple lines like
```yaml
user: {{ .Values.secret1 }}
pass: {{ .Values.secret2 }}
```
I get the proper result
```yaml
user: username
pass: mysecretpassword
```

### Environment

- Helmfile Version: 0.161.0
- Helm Version: 3.13.2
- Helm Secrets Version: 4.1.1

**Comment by Kellen275** [comment]
I've found that using `fetchSecretValue` can produce a correct result
```yaml
userPass: { .Values.secret1 | fetchSecretValue }ZZZ{ .Values.secret2 }
# yields
userPass: usernameZZZmysecretpassword
```
