### ISSUE TITLE
Unable to refer encrypted secret file present in the same folder as values.yaml

### ISSUE THREAD

**Issue by priyas16** [jkroepke/helm-secrets#471]
### Current Behavior

Hi Team,
We need to place few chart related files which are common for different clusters in order to avoid code redundancy and hence we have stored all the chart files in the common folder and the values.yaml and its encrypted secret file in the specific cluster folders using Applications in ArgoCD. But the deployment is failing, since it's unable to refer to the encrypted secret file alone.

Below is what we tried.

Scenario1:
```
source:
    repoURL: <GIT-URL>
    targetRevision: HEAD
    path: infrastructure/on-prem/common
    helm:
      valueFiles:
        - '../poc/splunk-monitoring/values.yaml'
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../poc/splunk-monitoring/accessToken.enc.yaml
```
Error:

Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template splunk-opentelemetry --namespace splunk-opentelemetry --kube-version 1.27 --values <path to cached source>/infrastructure/on-prem/poc/splunk-monitoring/values.yaml --values secrets+age-import:///helm-secrets-private-keys/key.txt?../poc/splunk-monitoring/accessToken.enc.yaml <api versions removed> --include-crds` failed exit status 1: [helm-secrets] Values filepath '../poc/splunk-monitoring/accessToken.enc.yaml' contains '..'. Path traversal is not allowed. [helm-secrets] File does not exist: ../poc/splunk-monitoring/accessToken.enc.yaml Error: plugin "scripts/run.sh downloader" exited with error

Scenario2:
```
source:
    repoURL: <GIT-URL>
    targetRevision: HEAD
    path: infrastructure/on-prem/common
    helm:
      valueFiles:
        - '../poc/splunk-monitoring/values.yaml'
        - secrets+age-import:///helm-secrets-private-keys/key.txt?git+<GIT-URL>/infrastructure/on-prem/poc/splunk-monitoring/accessToken.enc.yaml?ref=main
```
Error:

Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template splunk-opentelemetry --namespace splunk-opentelemetry --kube-version 1.27 --values <path to cached source>/infrastructure/on-prem/poc/splunk-monitoring/values.yaml --values secrets+age-import:///helm-secrets-private-keys/key.txt?git+<GIT_URL>/infrastructure/on-prem/poc/splunk-monitoring/accessToken.enc.yaml?ref=main <api versions removed> --include-crds` failed exit status 1: Error: failed parsing --set-file data: open git+<GIT_URL>/infrastructure/on-prem/poc/splunk-monitoring/accessToken.enc.yaml?ref=main: no such file or directory [helm-secrets] helm template command errored on value 'git+<GIT_URL>/infrastructure/on-prem/poc/splunk-monitoring/accessToken.enc.yaml?ref=main' [helm-secrets] File does not exist: git+<GIT_URL>/infrastructure/on-prem/poc/splunk-monitoring/accessToken.enc.yaml?ref=main Error: plugin "scripts/run.sh downloader" exited with error

Request you to help us in getting this resolved. Thanks!

### Expected Behavior

Deploying the helm chart.

### Environment

Helm Version: 3.14.0
Helm Secrets Version: 4.4.2
ArgoCD Version : V2.10.3
OS: RHEL 8.9
Shell: 4.4
