### ISSUE TITLE
Sops + gcp kms with Argocd multi source

### ISSUE THREAD

**Issue by stephaneetje** [jkroepke/helm-secrets#475]
Hello

I'm using sops backend with gcp kms (with workload identity) with argocd and it's working perfectly for non multi source apps.

I followed the instructions, added HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH and HELM_SECRETS_WRAPPER_ENABLED to repoServer.

I'm getting errors related to unfound values, it looks like it is reading encrypted values. Same values file unencrypted is accepted.

I was thinking it should work outofBox as it should be called the same way for multi or non multi app (on helm secrets side i mean). But documentation about multi source only talks about GPG, so is there a possibility using KMS would not be suported ?

### Environment

- Helm Secrets Version: 4.6.1
- ArgoCD Version: 2.10.7

**Comment by jkroepke** [comment]
Could you please run the following command on your argocd-repo-server?

```
ls -lah $(which helm)
```

**Comment by stephaneetje** [comment]
```$ ls -lah $(which helm)
-rwxr-xr-x 1 root root 51M Sep 26 06:39 /usr/local/bin/helm```

**Comment by jkroepke** [comment]
That means the helm wrapper is not active. Just set `HELM_SECRETS_WRAPPER_ENABLED` to true is not fully sufficient.

Please follow precisely the documentation at https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#step-1-customize-argocd-repo-server. 

At the end, a /usr/local/sbin/helm file should exists and it should be a shell script.

**Comment by stephaneetje** [comment]
Oh thanks!

I'm using init container, i do see how you link /usr/local/sbin/helm with the wrapper script in the Docker Documentation, but i don't find the equivalent for container init. Am i missing something?

**Comment by jkroepke** [comment]
Check volumeMount 

```
  volumeMounts:
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: gitops-tools
```

Please also check, if `/usr/local/sbin/` is part of the PATH env `echo $PATH`

**Comment by stephaneetje** [comment]
How could i miss that, thank you so much!

**Comment by jkroepke** [comment]
Any recommendation to the docs?

**Comment by stephaneetje** [comment]
Maybe in the multi source doc i would add in requirements that /usr/local/sbin must be a symlink to helm-wrapper.sh.

**Comment by jkroepke** [comment]
@stephaneetje I saw you post on the ArgoCD issue as well. Would mind to link to solution that other people with similar issues having a solution?

Thanks!

**Comment by stephaneetje** [comment]
No problem, just did it.

**Comment by chuyuou** [comment]
Ran into the same issue on aws KMS. This is how I install helm secrets: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
      - name: download-tools
        image: alpine:3.20.3
        command: [ sh, -ec ]
        env:
          - name: HELM_SECRETS_VERSION
            value: "4.6.2"
          - name: KUBECTL_VERSION
            value: "1.29.3"
          - name: VALS_VERSION
            value: "0.37.1"
          - name: SOPS_VERSION
            value: "3.8.1"
        args:
          - |
            ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')
            mkdir -p /gitops-tools/helm-plugins
            wget -qO- --no-check-certificate  https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /gitops-tools/helm-plugins -xzf-;
            wget -qO /gitops-tools/sops  --no-check-certificate  https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.${ARCH}
            wget -qO /gitops-tools/kubectl --no-check-certificate  https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${ARCH}/kubectl
            wget -qO- --no-check-certificate  https://github.com/variantdev/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_${ARCH}.tar.gz | tar -xzf- -C /gitops-tools/ vals;

            # helm secrets wrapper mode installation (optional)
            # RUN printf '#!/usr/bin/env sh\nexec %s secrets "$@"' "${HELM_SECRETS_HELM_PATH}" >"/usr/local/sbin/helm" && chmod +x "/gitops-tools/helm"
            chmod +x /gitops-tools/*
            cp /gitops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /gitops-tools/helm
        volumeMounts:
          - mountPath: /gitops-tools
            name: gitops-tools
      containers:
      - name: argocd-repo-server 
        volumeMounts:
        - mountPath: /gitops-tools
          name: gitops-tools
        - mountPath: /usr/local/sbin/helm
          subPath: helm
          name: gitops-tools
        - mountPath: /helm-secrets-private-keys/ # for AGE and GPG
          name: helm-secrets-private-keys
        env:
        - name: HELM_PLUGINS
          value: /gitops-tools/helm-plugins/
        - name: HELM_SECRETS_CURL_PATH
          value: /gitops-tools/curl
        - name: HELM_SECRETS_SOPS_PATH
          value: /gitops-tools/sops
        - name: HELM_SECRETS_VALS_PATH
          value: /gitops-tools/vals
        - name: HELM_SECRETS_KUBECTL_PATH
          value: /gitops-tools/kubectl
        - name: HELM_SECRETS_BACKEND
          value: sops
        # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
        - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
          value: "false"
        - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
          value: "true"
        - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
          value: "false"
        - name: HELM_SECRETS_WRAPPER_ENABLED
          value: "true"
        - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
          value: "true"
        - name: HELM_SECRETS_HELM_PATH
          value: /usr/local/bin/helm
      volumes:
        - name: gitops-tools
          emptyDir: {}
        - name: helm-secrets-private-keys
          secret:
            secretName: helm-secrets-private-keys
``` 
Also got:
```
$ ls -lah $(which helm)
-rwxr-xr-x. 1 root root 345 Feb 19 13:37 /gitops-tools/helm
$ cat /gitops-tools/helm
#!/usr/bin/env sh

if [ "${HELM_SECRETS_WRAPPER_ENABLED}" = "true" ]; then
    if [ "$1" = "install" ] || [ "$1" = "upgrade" ] || [ "$1" = "template" ] || [ "$1" = "lint" ] || [ "$1" = "diff" ]; then
        exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" secrets "$@"
    fi
fi

exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" "$@"
$
```

As for my argocd applicationset manifest: 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crowdstrike-falcon-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters: {}
          - git:
              repoURL: https://github.com/org/argocd.git
              revision: 1.2.3
              files:
                - path: 'clusters/nonprod/components/crowdstrike-falcon/{{.name}}-values.yaml'
  template:
    metadata:
      name: '{{ .name }}-{{ .path.basename }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "40"
    spec:
      project: infrastructure
      sources:
        - repoURL: https://crowdstrike.github.io/falcon-helm
          chart: falcon-sensor
          targetRevision: '{{ .chartVersion }}'
          helm:
            valueFiles:
              - '$valueFileRef/{{.path.path}}/{{.path.filename}}' 
              - '$valueFileRef/{{.path.path}}/{{ .name }}-secrets.yaml'
        - repoURL: https://github.com/org/argocd.git
          targetRevision: 1.2.3
          ref: valueFileRef
      destination:
        server: '{{ .server }}'
        namespace: falcon-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
```
It could find the file, cause if I use a normal unencrypted file, it could get the value. However, it couldn't decrypt and complains 
```
failed exit status 1: Error: values don't meet the specifications of the schema(s) in the following chart(s):
```
Have I missed anything? @jkroepke
