### ISSUE TITLE
Protocol handler from terminal

### ISSUE THREAD

**Issue by hegawa** [jkroepke/helm-secrets#477]
### Current Behavior

- Given that I have a `values.yaml` file that contains a GCP Secrets reference
```yaml
somekey: ref+gcpsecrets://someProjectId/SecretKeyID
```
- And I have done `export HELM_SECRETS_BACKEND="vals"`
- when I run `helm secrets decrypt ./values.yaml` it successfully fetches the secret 

### Expected Behavior

- when I run `helm template . -f secrets://values.yaml` it should also fetch the secrets if i understand the protocol handler documentation correctly

### Steps To Reproduce

```markdown
1. create a values.yaml file for any chart
2. enter `ref+gcpsecrets://toyourprojectID/keyThatExistsID`
3. run `helm template . -f secrets://values/yaml`

it errors with 

Error: fork/exec /home/yourUserName/.local/share/helm/plugins/helm-secrets/scripts/wrapper/run.cmd: exec format error
```

### Environment

- Helm Version: 3.15.4
- Helm Secrets Version: 4.6.2-dev
- ArgoCD Version: None
- OS: ubuntu
- Shell: Bash

**Comment by jkroepke** [comment]
Are you running helm secrets inside WSL?

**Comment by hegawa** [comment]
yep i am running wsl with the ubuntu! and also our ci/cd will be on ubuntu image on azure pipeline if that also differs in behavior
the result of `which helm` is `/usr/sbin/helm`

**Comment by jkroepke** [comment]
Please re-reun your command which helm --debug template.

At some point, helm thinks i'm on Windows.

**Comment by hegawa** [comment]
hello! I ran `helm template . -f secrets://secrettest.yaml --debug`

```
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /home/ubuntu/code/helm/sandbox-app

Error: fork/exec /home/ubuntu/.local/share/helm/plugins/helm-secrets/scripts/wrapper/run.cmd: exec format error
helm.go:84: [debug] fork/exec /home/ubuntu/.local/share/helm/plugins/helm-secrets/scripts/wrapper/run.cmd: exec format error
```

the same diretory and file i have already confirmed that 
- I can run `helm secret template . -f secrettest,yaml` no problem
- I can also do 'helm secret decrypt secrettest.yaml` confirmed that it also works
- I ran vals against it and it also worked

**Comment by jkroepke** [comment]
What is the output of that command:

```
cat "$(helm env HELM_PLUGINS)"/*secrets*/plugin.yaml
```

**Comment by hegawa** [comment]
it is 
```yaml
name: "secrets"
version: "4.6.2-dev"
usage: "Secrets encryption in Helm for Git storing"
description: |-
  This plugin provides secrets values encryption for Helm charts secure storing
useTunnel: false
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
platformCommand:
  - os: windows
    command: >-
      cmd /c $HELM_PLUGIN_DIR\scripts\wrapper\run.cmd

downloaders:
  - command: "scripts/wrapper/run.cmd downloader"
    protocols:
      - "secrets"
      - "secrets+gpg-import"
      - "secrets+gpg-import-kubernetes"
      - "secrets+age-import"
      - "secrets+age-import-kubernetes"
      - "secrets+literal"
```

**Comment by hegawa** [comment]
- `helm template . -f secrets://secrettest.yaml` results in 
```bash
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /home/ubuntu/code/common-chart/common-chart/chart-migration-test/helm/projects/sandbox-app

Error: fork/exec /home/ubuntu/.local/share/helm/plugins/helm-secrets/scripts/wrapper/run.cmd: exec format error
helm.go:84: [debug] fork/exec /home/ubuntu/.local/share/helm/plugins/helm-secrets/scripts/wrapper/run.cmd: exec format error
```
- i uninstall secrets and reinstalled with `helm plugin install https://github.com/jkroepke/helm-secrets`

- cat result of plugin.yaml
```yaml
name: "secrets"
version: "4.6.2"
usage: "Secrets encryption in Helm for Git storing"
description: |-
  This plugin provides secrets values encryption for Helm charts secure storing
useTunnel: false
command: "$HELM_PLUGIN_DIR/scripts/run.sh"
platformCommand:
  - os: windows
    command: >-
      cmd /c $HELM_PLUGIN_DIR\scripts\wrapper\run.cmd

downloaders:
  - command: "scripts/wrapper/run.cmd downloader"
    protocols:
      - "secrets"
      - "secrets+gpg-import"
      - "secrets+gpg-import-kubernetes"
      - "secrets+age-import"
      - "secrets+age-import-kubernetes"
      - "secrets+literal"

```
