### ISSUE TITLE
Issues using AWS Secrets Manager from Helm Template

### ISSUE THREAD

**Issue by mwdomino** [jkroepke/helm-secrets#483]
### Current Behavior

Hey all, sorry if this is the wrong way to report it. Almost certainly not a bug and just me holding it wrong. I have done the following:

1. Set up ArgoCD repo-server with a custom container including helm-secrets:
```
$ which helm
/usr/local/sbin/helm
$ cat /usr/local/sbin/helm
#!/usr/bin/env sh

if [ "${HELM_SECRETS_WRAPPER_ENABLED}" = "true" ]; then
    if [ "$1" = "install" ] || [ "$1" = "upgrade" ] || [ "$1" = "template" ] || [ "$1" = "lint" ] || [ "$1" = "diff" ]; then
        exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" secrets "$@"
    fi
fi

exec "${HELM_SECRETS_HELM_PATH:-${HELM_BIN:-"helm"}}" "$@"
```

2. Created an ArgoCD application:
```
{{- range .Values.workloadClusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .name }}-app1"
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: https://github.com/<org>/<repo>.git
    targetRevision: HEAD
    path: ./apps/aoa_poc/workload/app1
    helm:
      parameters:
      - name: "clusterInfo.name"
        value: {{ .name }}
      - name: "clusterInfo.location"
        value: {{ .clusterInfo.location }}
      - name: helm-secrets-backend
        value: vals
  destination:
    server: "{{ .server }}"
    namespace: app1
  syncPolicy:
{{- if $.Values.app1.autoSync }}
    automated: {}
{{- end }}
    syncOptions:
      - CreateNamespace=true
{{- end }}
```

3. Included a test secret in that app1 repository's Helm chart:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: test-helm-secret
type: Opaque
stringData:
  password: "ref+awssecrets:///dev/cluster-0/testsecret"
```

### Expected Behavior

When I run this command locally, it templates properly and substitutes the secret:
```
HELM_SECRETS_BACKEND=vals helm secrets decrypt ./templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: test-helm-secret
stringData:
  password: secret for cluster-0
type: Opaque
```

I'd like the same behavior when deploying from ArgoCD.

### Environment

- Helm Version: 3.16.1
- Helm Secrets Version: 4.6.2
- ArgoCD Version: 2.14.2
- OS: Talos Linux cluster/NixOS dev box
- Shell: zsh

### Anything else?

Thanks in advance for any help, I'm probably just missing a simple step here :)
