### ISSUE TITLE
Secret data keeps disappearing and reappearing per 10 seconds in argo

### ISSUE THREAD

**Issue by chuyuou** [jkroepke/helm-secrets#494]
### Current Behavior
Argo keeps to sync the app with the secret per 10 seconds. The status of the app keeps looping similarly as below:
```
 Normal  OperationStarted    12s    argocd-application-controller  Initiated automated sync to 'fdf03exxxxxx'
  Normal  ResourceUpdated     12s    argocd-application-controller  Updated sync status: Synced -> OutOfSync
  Normal  ResourceUpdated     9s     argocd-application-controller  Updated sync status: OutOfSync -> Synced
  Normal  OperationCompleted  8s     argocd-application-controller  Sync operation to fdf03exxxxxx succeeded
``` 
When we check the value of the secret, the expected values keeps appearing and disappearing roughly per 10-15 seconds as well: 

![Image](https://github.com/user-attachments/assets/0e9001be-70c6-4f84-a0b7-193d719a2ff0)

 
### Expected Behavior
Secret should be stable 

 
### Steps To Reproduce

```markdown

```

### Environment

- Helm Version:
- Helm Secrets Version: 4.6.2
- SOPS version:3.9.0
- ArgoCD Version:2.12.3
- OS:
- Shell:

**Comment by jkroepke** [comment]
If possible, check audit log of kubernetes for who is invoke the delete of the secret.

**Comment by chuyuou** [comment]
> If possible, check audit log of kubernetes for who is invoke the delete of the secret.

It's `argocd-application-controller` keeps on patching the secret. @jkroepke

**Comment by jkroepke** [comment]
How you install helm-secrets on ArgoCD?

**Comment by chuyuou** [comment]
> How you install helm-secrets on ArgoCD?

I installed based on https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration, using custom docker image

**Comment by jkroepke** [comment]
The Dockerfile seems incomplete. At least all env variables are not defined.

**Comment by chuyuou** [comment]
> The Dockerfile seems incomplete. At least all env variables are not defined, only. PATH

Oh apologies, the env for argocd-repo-server is as: 
```
        env:
          - name: HELM_PLUGINS
            value: /gitops-tools/helm-plugins/
          - name: HELM_SECRETS_SOPS_PATH
            value: /gitops-tools/sops
          - name: HELM_SECRETS_VALS_PATH
            value: /gitops-tools/vals
          - name: HELM_SECRETS_KUBECTL_PATH
            value: /gitops-tools/kubectl
          - name: HELM_SECRETS_CURL_PATH
            value: /gitops-tools/curl
          - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
            value: "true"
          - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
            value: "true"
          - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
            value: "true"
          - name: SOPS_AGE_KEY_FILE # For age,need to specify this to enable local
            value: /helm-secrets-private-keys/key.txt
```
