### ISSUE TITLE
Helm-secrets shows shows credentials in plain view when using multiple valueFiles [SOPS]

### ISSUE THREAD

**Issue by luciano-buono** [jkroepke/helm-secrets#495]
### Current Behavior

Until now I used an ArgoCD application with a single values file as below:

```yaml
project: default
source:
  repoURL: 'git@github.com:...'
  path: apps/prod
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argo-cd
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
```

While in my values.yaml file had a line like:

```yaml
          files:
            backend:
              stringData:
                POSTGRES_USERNAME: backend-user
                POSTGRES_PASSWORD: ref+sops://ewoJImRhdGEiOiAi...?key_type=base64
```

---
Now I decided to split my values.yaml in multiple files to allow better readability  (this `apps` Application is following an Apps of Apps pattern):

```yaml
project: default
source:
  repoURL: 'git@github.com:...'
  path: apps/prod
  targetRevision: feature/split-apps
  helm:
    valueFiles:
      - values-backend.yaml
      - values-frontend.yaml
      - values-root.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argo-cd
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
```

While this works, I now face this issue:

![Image](https://github.com/user-attachments/assets/33987d88-8849-4fe3-839e-9cd8eaee3bbc)

The credentials are shown unencrypted directly in ArgoCD. I don't really understand why may cause this since the overall logic is completely the same

### Expected Behavior

Credentials should still be shown as `ref+sops://ewoJImRhdGEiOiAi...?key_type=base64`

### Steps To Reproduce

```markdown

```

### Environment

- Helm Version:
- Helm Secrets Version:
- ArgoCD Version
- OS:
- Shell:

**Comment by jkroepke** [comment]
files with encrypted values require the `secrets://` prefix, e..g `secrets://values-frontend.yaml`

**Comment by luciano-buono** [comment]
@jkroepke I have tried adding all the files with the prefix but i still see the sensitive data in plainview

```yaml
  path: apps/prod
  targetRevision: feature/split-apps
  helm:
    valueFiles:
      - 'secrets://values-backend.yaml'
      - 'secrets://values-frontend.yaml'
      - 'secrets://values-root.yaml'
```

![Image](https://github.com/user-attachments/assets/f15e9a26-167f-4ee6-9280-7dfe2bb7269c)

**Comment by jkroepke** [comment]
Sometime, you need a "hard reload" in ArgoCD, since the cache based on the git commit.

![Image](https://github.com/user-attachments/assets/0508e6fa-5e78-4f32-bf65-beb1bff2d607)

**Comment by luciano-buono** [comment]
@jkroepke, I have tried hard refreshing via GUI and also manually restarting repo-server pod.
It's not a cache problem.

I have also tried using a single valuefile:

```yaml
  path: apps/prod
  targetRevision: main
  helm:
    valueFiles:
      - 'secrets://values.yaml'
```

and it still shows the unencrypted data in plainview.
Seems odd why if we remove the `valueFiles` and it automatically looks for the values.yaml, this does not happen
