### ISSUE TITLE
Path traversal is not allowed

### ISSUE THREAD

**Issue by nicefuture2016** [jkroepke/helm-secrets#496]
```yaml
project: test
source:
  repoURL: 'https://test.com/user/devops-charts.git'
  path: charts/application
  targetRevision: argocd-test
  helm:
    valueFiles:
      - >-
        secrets+gpg-import:///helm-secrets-private-keys/key.asc?../../helm-values/new-buss/application/values-new-buss-project.yaml
    releaseName: new-buss-project
destination:
  server: 'https://10.1.1.1:6443'
  namespace: new-buss
syncPolicy:
  syncOptions:
    - Validate=false
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
```
My chart package and my values file are located in different directories. When I create an Argo CD application, the following error occurs.

`Values filepath '../../helm-values/new-buss/application/values-new-buss-project.yaml' contains '..'. Path traversal is not allowed. `

How can this issue be resolved?
