### ISSUE TITLE
helm_wrapper does not honor escaped commas in --set arguments

### ISSUE THREAD

**Issue by metrictwo** [jkroepke/helm-secrets#499]
### Current Behavior

The `helm_wrapper` function does not allow escaping commas in `--set` arguments. When using `helm secrets` or the wrapper with a test chart:
```
% helm secrets template helm-charts/helm-secrets-bug --set "payload=1\,2\,3"
---
# Source: helm-secrets-bug/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: of-little-consequence
data:
  payload: |
    null
```

### Expected Behavior

This is what we get with vanilla helm:
```
% helm template helm-charts/helm-secrets-bug --set "payload=1\,2\,3"
---
# Source: helm-secrets-bug/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: of-little-consequence
data:
  payload: |
    "1,2,3"
```

### Steps To Reproduce
Using a simple test chart with a single template:
```markdown
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: of-little-consequence
data:
  payload: |
    {{ toJson .Values.payload | required "must specify payload" }}
```
Attempt to pass in any string, nested or otherwise, that contains commas that have been escaped properly per the helm [docs](https://helm.sh/docs/intro/using_helm/#the-format-and-limitations-of---set), such as one pasted above.

### Environment

- Helm Version: any
- Helm Secrets Version: 4.5.1
- ArgoCD Version: 2.10.6
- OS: MacOS 15.2
- Shell: zsh locally, bash on `argocd-repo-server` custom image

### Anything else?

This seems to be due to a big [here](https://github.com/jkroepke/helm-secrets/blob/main/scripts/commands/helm.sh#L85-L90), which finds escaped commas, but only saves one delimited piece rather than accumulating them. I fixed this locally like so:
```
                case "${literal}" in
                *\\)
                    if [ "${_literal}" != "" ]; then
                      _literal="${_literal},${literal}"
                    else
                      _literal="${literal}"
                    fi
                    continue
                    ;;
                esac
```
