### ISSUE TITLE
Argo CD known limitation calrification

### ISSUE THREAD

**Issue by jacek-jablonski** [jkroepke/helm-secrets#504]
Hi,
I've got trouble understanding Argo CD integration known limitation: https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#known-limitations
What exactly does "External Chart and local values" mean?
Problematic Application manifest looks like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.1
    chart: ingress-nginx

    helm:
      releaseName: ingress-nginx
      valueFiles:
        - secrets://secrets.yaml
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

Where does the `secret.yaml` file come from in above example?
