### ISSUE TITLE
Secrets are not being fetched from AWS Secrets manager in ArgoCD

### ISSUE THREAD

**Issue by darnone** [jkroepke/helm-secrets#524]
### Current Behavior

We are moving our deployments to ArgoCD on AWS EKS and some of our chart values use the vals backend to fetch secrets. I have patched the argocd-repo-server with the below kustomize and added the AWS IRSA the argocd-server and argocd-repo-server service accounts (attached). Everything looks correct. My sample helm chart only has a secret that looks like:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret
stringData:
  
[secret.yaml.txt](https://github.com/user-attachments/files/20105949/secret.yaml.txt)

: {{ .Values.jdbc_url }}
```

values for the chart have one value:

```
jdbc_url: ref+awssecrets://gts-argocd-ci-dev#/sonarqube_jdbc_url
```
When I deploy the helm chart with an argocd application, the chart deploy but the resulting secret places the string "ref+awssecrets://gts-argocd-ci-dev#/sonarqube_jdbc_url" as the value instead of the secret on AWS. If I change the `stringData` to `data`, it does the same. I don't know if this is a bug but  sure where I am going wrong.

Argocd Repo Patch
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        env:
        # Change Helm plugins dir to the shared volume
        - name: HELM_PLUGINS
          value: /gitops-tools/helm-plugins/
          # Tell Helm Secrets plugin to use tools at specific paths
        - name: HELM_SECRETS_SOPS_PATH
          value: /gitops-tools/sops
        - name: HELM_SECRETS_VALS_PATH
          value: /gitops-tools/vals
        - name: HELM_SECRETS_KUBECTL_PATH
          value: /gitops-tools/kubectl
        - name: HELM_SECRETS_CURL_PATH
          value: /gitops-tools/curl
        - name: HELM_SECRETS_BACKEND
          value: vals
        - name: HELM_SECRETS_WRAPPER_ENABLED
          value: "true"
        - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
          value: "true"
        - name: HELM_SECRETS_HELM_PATH
          value: /usr/local/bin/helm
        - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
          value: "false"
        - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
          value: "false"
        - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
          value: "false"
        volumeMounts:
        - mountPath: /gitops-tools
          name: gitops-tools
        - mountPath: /usr/local/sbin/helm
          subPath: helm
          name: gitops-tools
      initContainers:
      - name: download-tools
        image: alpine:latest
        command: [sh, -ec]
        args:
          - |
            set -x
            mkdir -p /gitops-tools/helm-plugins

            GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/')
            wget -qO "/gitops-tools/curl" "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-${GO_ARCH}"

            GO_ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')
            wget -qO "/gitops-tools/kubectl" "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/${GO_ARCH}/kubectl" 
            wget -qO "/gitops-tools/sops" "https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.${GO_ARCH}"
            wget -qO- "https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_${GO_ARCH}.tar.gz" | tar zxv -C /gitops-tools vals
            wget -qO- "https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz" | tar -C /gitops-tools/helm-plugins -xzf-

            chmod +x /gitops-tools/*
            cp /gitops-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /gitops-tools/helm
        env:
          - name: HELM_SECRETS_VERSION
            value: "4.6.3"
          - name: KUBECTL_VERSION
            value: "1.30.12"
          - name: VALS_VERSION
            value: "0.40.1"
          - name: SOPS_VERSION
            value: "3.10.2"
        volumeMounts:
        - mountPath: /gitops-tools
          name: gitops-tools
      volumes:
      - name: gitops-tools
        emptyDir: {}
```

### Expected Behavior

When I deploy the argocd application I would expect the `mysql-url` key to map to the value in AWS Secrets Manager.

### Steps To Reproduce

```markdown
ArgoCD 3.0.0
Patch repo server
Add IRSA to argocd-server and argocd-repo-server
apply argocd application helm chart
```

### Environment

- Helm Version: 3.17.1
- Helm Secrets Version: 4.6.3
- ArgoCD Version: 3.0.0 (argocd-autpilot v0.14.18
- OS: Linux 5.10.230-223.885.amzn2.x86_64 
- Shell: sh

### Anything else?

https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration

**Comment by darnone** [comment]
I have verified that if I copy the helm chart to the argocd-repo-server the following will fetch the secret:
```
helm secrets --evaluate-templates template helm-secret-plugin ./charts/helm-secret-plugin/ -n helm-secret-plugin
apiVersion: v1
kind: Secret
metadata:
  name: secret
stringData:
  mysql-url: jdbc:postgresql://gts-argocd-ci-sonarqube-dev.cpq13tymdi19.us-east-1.rds.amazonaws.com:5432/sonarqube
```

So I assume this means the argocd-repo-server patch is correct.

**Comment by darnone** [comment]
so I got this to work:
```
helm:
    parameters:
    - name: jdbc_url
       value: secrets+literal://ref+awssecrets://gts-argocd-ci-dev#/sonarqube_jdbc_url
```
 but It did not work of I set `jdbc_url` in a values file:

```
jdbc_url: secrets+literal://ref+awssecrets://gts-argocd-ci-dev#/sonarqube_jdbc_url 
```
It gave me the string again>

Is there a way to get this to work from a values file?
